/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../app/search/search.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/router/src/router_state';
import * as import9 from '../../../app/api/search.service';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from './search.component.css.shim';
import * as import13 from '../../../app/now-playing/zone-selector/zone-selector.component';
import * as import14 from '../../../app/shared/search-bar/search-bar.component';
import * as import15 from '../../../app/shared/breadcrumbs/breadcrumbs.component';
import * as import16 from '../../../app/shared/tabset/tabset.component';
import * as import17 from '@angular/core/src/linker/query_list';
import * as import18 from '@angular/common/src/directives/ng_if';
import * as import19 from '../now-playing/zone-selector/zone-selector.component.ngfactory';
import * as import20 from '../../../app/api/audio-zone.service';
import * as import21 from '../shared/search-bar/search-bar.component.ngfactory';
import * as import22 from '@angular/router/src/router';
import * as import23 from '../shared/breadcrumbs/breadcrumbs.component.ngfactory';
import * as import24 from '@angular/common/src/location/location';
import * as import25 from '../shared/tabset/tabset.component.ngfactory';
import * as import26 from '@angular/core/src/linker/template_ref';
import * as import27 from '@angular/core/src/security';
import * as import28 from '../../../app/shared/tabset/tab/tab.component';
import * as import29 from '@angular/common/src/directives/ng_for';
import * as import30 from '../shared/tabset/tab/tab.component.ngfactory';
import * as import31 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import32 from '../../../app/search/artist-list-item/artist-list-item.component';
import * as import33 from './artist-list-item/artist-list-item.component.ngfactory';
import * as import34 from '../../../app/search/album-list-item/album-list-item.component';
import * as import35 from './album-list-item/album-list-item.component.ngfactory';
import * as import36 from '../../../app/shared/track-list-item/track-list-item.component';
import * as import37 from '../shared/track-list-item/track-list-item.component.ngfactory';
import * as import38 from '../../../app/api/queue.service';
var renderType_SearchComponent_Host:import0.RenderComponentType = (null as any);
class _View_SearchComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _SearchComponent_0_4:import3.SearchComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SearchComponent_Host0,renderType_SearchComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-search',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SearchComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SearchComponent_0_4 = new import3.SearchComponent(this.parentInjector.get(import8.ActivatedRoute),this.parentInjector.get(import9.SearchService));
    this._appEl_0.initComponent(this._SearchComponent_0_4,[],compView_0);
    compView_0.create(this._SearchComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.SearchComponent) && (0 === requestNodeIndex))) { return this._SearchComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._SearchComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SearchComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_SearchComponent_Host === (null as any))) { (renderType_SearchComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,[],{})); }
  return new _View_SearchComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const SearchComponentNgFactory:import11.ComponentFactory<import3.SearchComponent> = new import11.ComponentFactory<import3.SearchComponent>('app-search',viewFactory_SearchComponent_Host0,import3.SearchComponent);
const styles_SearchComponent:any[] = [import12.styles];
var renderType_SearchComponent:import0.RenderComponentType = (null as any);
class _View_SearchComponent0 extends import1.AppView<import3.SearchComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _ZoneSelectorComponent_9_4:import13.ZoneSelectorComponent;
  _text_10:any;
  _el_11:any;
  /*private*/ _appEl_11:import2.AppElement;
  _SearchBarComponent_11_4:import14.SearchBarComponent;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import2.AppElement;
  _BreadcrumbsComponent_14_4:import15.BreadcrumbsComponent;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  /*private*/ _appEl_25:import2.AppElement;
  _TabsetComponent_25_4:import16.TabsetComponent;
  _query_TabComponent_25_0:import17.QueryList<any>;
  _text_26:any;
  _anchor_27:any;
  /*private*/ _appEl_27:import2.AppElement;
  _TemplateRef_27_5:any;
  _NgIf_27_6:import18.NgIf;
  _text_28:any;
  _anchor_29:any;
  /*private*/ _appEl_29:import2.AppElement;
  _TemplateRef_29_5:any;
  _NgIf_29_6:import18.NgIf;
  _text_30:any;
  _anchor_31:any;
  /*private*/ _appEl_31:import2.AppElement;
  _TemplateRef_31_5:any;
  _NgIf_31_6:import18.NgIf;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SearchComponent0,renderType_SearchComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','app-root');
    this._text_1 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','album-art-background');
    this._el_3 = this.renderer.createElement(this._el_2,'img',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','content-top search-header');
    this._text_6 = this.renderer.createText(this._el_5,'\n		',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'div',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','row nav-bar');
    this._text_8 = this.renderer.createText(this._el_7,'\n			',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'zone-selector',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','col-xs-3');
    this._appEl_9 = new import2.AppElement(9,7,this,this._el_9);
    var compView_9:any = import19.viewFactory_ZoneSelectorComponent0(this.viewUtils,this.injector(9),this._appEl_9);
    this._ZoneSelectorComponent_9_4 = new import13.ZoneSelectorComponent(this.parentInjector.get(import20.AudioZoneService));
    this._appEl_9.initComponent(this._ZoneSelectorComponent_9_4,[],compView_9);
    compView_9.create(this._ZoneSelectorComponent_9_4,[],(null as any));
    this._text_10 = this.renderer.createText(this._el_7,'\n			',(null as any));
    this._el_11 = this.renderer.createElement(this._el_7,'search-bar',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','col-xs-9');
    this._appEl_11 = new import2.AppElement(11,7,this,this._el_11);
    var compView_11:any = import21.viewFactory_SearchBarComponent0(this.viewUtils,this.injector(11),this._appEl_11);
    this._SearchBarComponent_11_4 = new import14.SearchBarComponent(this.parentInjector.get(import22.Router));
    this._appEl_11.initComponent(this._SearchBarComponent_11_4,[],compView_11);
    compView_11.create(this._SearchBarComponent_11_4,[],(null as any));
    this._text_12 = this.renderer.createText(this._el_7,'\n		',(null as any));
    this._text_13 = this.renderer.createText(this._el_5,'\n		',(null as any));
    this._el_14 = this.renderer.createElement(this._el_5,'breadcrumbs',(null as any));
    this._appEl_14 = new import2.AppElement(14,5,this,this._el_14);
    var compView_14:any = import23.viewFactory_BreadcrumbsComponent0(this.viewUtils,this.injector(14),this._appEl_14);
    this._BreadcrumbsComponent_14_4 = new import15.BreadcrumbsComponent(this.parentInjector.get(import24.Location));
    this._appEl_14.initComponent(this._BreadcrumbsComponent_14_4,[],compView_14);
    compView_14.create(this._BreadcrumbsComponent_14_4,[],(null as any));
    this._text_15 = this.renderer.createText(this._el_5,'\n\n		',(null as any));
    this._el_16 = this.renderer.createElement(this._el_5,'div',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','search-term');
    this._text_17 = this.renderer.createText(this._el_16,'\n			Search results for ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_16,'em',(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'',(null as any));
    this._text_20 = this.renderer.createText(this._el_16,'\n		',(null as any));
    this._text_21 = this.renderer.createText(this._el_5,'\n	',(null as any));
    this._text_22 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_23 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','content-bottom');
    this._text_24 = this.renderer.createText(this._el_23,'\n		',(null as any));
    this._el_25 = this.renderer.createElement(this._el_23,'tabset',(null as any));
    this._appEl_25 = new import2.AppElement(25,23,this,this._el_25);
    var compView_25:any = import25.viewFactory_TabsetComponent0(this.viewUtils,this.injector(25),this._appEl_25);
    this._TabsetComponent_25_4 = new import16.TabsetComponent();
    this._query_TabComponent_25_0 = new import17.QueryList<any>();
    this._appEl_25.initComponent(this._TabsetComponent_25_4,[],compView_25);
    this._text_26 = this.renderer.createText((null as any),'\n			',(null as any));
    this._anchor_27 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_27 = new import2.AppElement(27,25,this,this._anchor_27);
    this._TemplateRef_27_5 = new import26.TemplateRef_(this._appEl_27,viewFactory_SearchComponent1);
    this._NgIf_27_6 = new import18.NgIf(this._appEl_27.vcRef,this._TemplateRef_27_5);
    this._text_28 = this.renderer.createText((null as any),'\n			',(null as any));
    this._anchor_29 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_29 = new import2.AppElement(29,25,this,this._anchor_29);
    this._TemplateRef_29_5 = new import26.TemplateRef_(this._appEl_29,viewFactory_SearchComponent4);
    this._NgIf_29_6 = new import18.NgIf(this._appEl_29.vcRef,this._TemplateRef_29_5);
    this._text_30 = this.renderer.createText((null as any),'\n			',(null as any));
    this._anchor_31 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_31 = new import2.AppElement(31,25,this,this._anchor_31);
    this._TemplateRef_31_5 = new import26.TemplateRef_(this._appEl_31,viewFactory_SearchComponent7);
    this._NgIf_31_6 = new import18.NgIf(this._appEl_31.vcRef,this._TemplateRef_31_5);
    this._text_32 = this.renderer.createText((null as any),'\n		',(null as any));
      compView_25.create(this._TabsetComponent_25_4,[[].concat([
        this._text_26,
        this._appEl_27,
        this._text_28,
        this._appEl_29,
        this._text_30,
        this._appEl_31,
        this._text_32
      ]
    )],(null as any));
    this._text_33 = this.renderer.createText(this._el_23,'\n	',(null as any));
    this._text_34 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._anchor_27,
      this._text_28,
      this._anchor_29,
      this._text_30,
      this._anchor_31,
      this._text_32,
      this._text_33,
      this._text_34
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.ZoneSelectorComponent) && (9 === requestNodeIndex))) { return this._ZoneSelectorComponent_9_4; }
    if (((token === import14.SearchBarComponent) && (11 === requestNodeIndex))) { return this._SearchBarComponent_11_4; }
    if (((token === import15.BreadcrumbsComponent) && (14 === requestNodeIndex))) { return this._BreadcrumbsComponent_14_4; }
    if (((token === import26.TemplateRef) && (27 === requestNodeIndex))) { return this._TemplateRef_27_5; }
    if (((token === import18.NgIf) && (27 === requestNodeIndex))) { return this._NgIf_27_6; }
    if (((token === import26.TemplateRef) && (29 === requestNodeIndex))) { return this._TemplateRef_29_5; }
    if (((token === import18.NgIf) && (29 === requestNodeIndex))) { return this._NgIf_29_6; }
    if (((token === import26.TemplateRef) && (31 === requestNodeIndex))) { return this._TemplateRef_31_5; }
    if (((token === import18.NgIf) && (31 === requestNodeIndex))) { return this._NgIf_31_6; }
    if (((token === import16.TabsetComponent) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._TabsetComponent_25_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = this.context.activeZone;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._ZoneSelectorComponent_9_4.activeZone = currVal_1;
      this._expr_1 = currVal_1;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ZoneSelectorComponent_9_4.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._SearchBarComponent_11_4.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._BreadcrumbsComponent_14_4.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TabsetComponent_25_4.ngOnInit(); }
    const currVal_4:any = ((this.context.results == (null as any))? (null as any): ((this.context.results.PagedArtists == (null as any))? (null as any): this.context.results.PagedArtists.Artists));
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgIf_27_6.ngIf = currVal_4;
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = ((this.context.results == (null as any))? (null as any): ((this.context.results.PagedAlbums == (null as any))? (null as any): this.context.results.PagedAlbums.Albums));
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._NgIf_29_6.ngIf = currVal_5;
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = ((this.context.results == (null as any))? (null as any): ((this.context.results.PagedTracks == (null as any))? (null as any): this.context.results.PagedTracks.Tracks));
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._NgIf_31_6.ngIf = currVal_6;
      this._expr_6 = currVal_6;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_TabComponent_25_0.dirty) {
        this._query_TabComponent_25_0.reset([
          this._appEl_27.mapNestedViews(_View_SearchComponent1,(nestedView:_View_SearchComponent1):any => {
            return [nestedView._TabComponent_0_4];
          }),
          this._appEl_29.mapNestedViews(_View_SearchComponent4,(nestedView:_View_SearchComponent4):any => {
            return [nestedView._TabComponent_0_4];
          }),
          this._appEl_31.mapNestedViews(_View_SearchComponent7,(nestedView:_View_SearchComponent7):any => {
            return [nestedView._TabComponent_0_4];
          })
        ]
        );
        this._TabsetComponent_25_4.tabs = this._query_TabComponent_25_0;
        this._query_TabComponent_25_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._TabsetComponent_25_4.ngAfterContentInit(); }
    }
    const currVal_0:any = (((this.context.album == (null as any))? (null as any): this.context.album.ArtworkUrlLarge) || '/assets/images/pixel.gif');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_3,'src',this.viewUtils.sanitizer.sanitize(import27.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    const currVal_2:any = import4.interpolate(1,'',this.context.searchQuery,'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_19,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._TabsetComponent_25_4.clazz;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_25,'tab-container',currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_SearchComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.SearchComponent> {
  if ((renderType_SearchComponent === (null as any))) { (renderType_SearchComponent = viewUtils.createRenderComponentType('C:/data/solutions/PlayMeExtension/src/app/search/search.component.html',0,import10.ViewEncapsulation.Emulated,styles_SearchComponent,{})); }
  return new _View_SearchComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_SearchComponent1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _TabComponent_0_4:import28.TabComponent;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import18.NgIf;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _anchor_6:any;
  /*private*/ _appEl_6:import2.AppElement;
  _TemplateRef_6_5:any;
  _NgFor_6_6:import29.NgFor;
  _text_7:any;
  _text_8:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SearchComponent1,renderType_SearchComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'tab',(null as any));
    this.renderer.setElementAttribute(this._el_0,'heading','Artists');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import30.viewFactory_TabComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._TabComponent_0_4 = new import28.TabComponent();
    this._appEl_0.initComponent(this._TabComponent_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n				',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import26.TemplateRef_(this._appEl_2,viewFactory_SearchComponent2);
    this._NgIf_2_6 = new import18.NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText((null as any),'\n				',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','row');
    this._text_5 = this.renderer.createText(this._el_4,'\n					',(null as any));
    this._anchor_6 = this.renderer.createTemplateAnchor(this._el_4,(null as any));
    this._appEl_6 = new import2.AppElement(6,4,this,this._anchor_6);
    this._TemplateRef_6_5 = new import26.TemplateRef_(this._appEl_6,viewFactory_SearchComponent3);
    this._NgFor_6_6 = new import29.NgFor(this._appEl_6.vcRef,this._TemplateRef_6_5,this.parent.parentInjector.get(import31.IterableDiffers),this.parent.ref);
    this._text_7 = this.renderer.createText(this._el_4,'\n				',(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n			',(null as any));
      compView_0.create(this._TabComponent_0_4,[[].concat([
        this._text_1,
        this._appEl_2,
        this._text_3,
        this._el_4,
        this._text_8
      ]
    )],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'select',this.eventHandler(this._handle_select_0_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    const subscription_0:any = this._TabComponent_0_4.select.subscribe(this.eventHandler(this._handle_select_0_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._anchor_6,
      this._text_7,
      this._text_8
    ]
    ,[disposable_0],[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import26.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import18.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6; }
    if (((token === import26.TemplateRef) && (6 === requestNodeIndex))) { return this._TemplateRef_6_5; }
    if (((token === import29.NgFor) && (6 === requestNodeIndex))) { return this._NgFor_6_6; }
    if (((token === import28.TabComponent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._TabComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_1:any = 'Artists';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._TabComponent_0_4.heading = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this.parent.context.artistTabActive;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._TabComponent_0_4.active = currVal_2;
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = (((this.parent.context.results == (null as any))? (null as any): ((this.parent.context.results.PagedArtists == (null as any))? (null as any): ((this.parent.context.results.PagedArtists.Artists == (null as any))? (null as any): this.parent.context.results.PagedArtists.Artists.length))) === 0);
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgIf_2_6.ngIf = currVal_3;
      this._expr_3 = currVal_3;
    }
    changes = (null as any);
    const currVal_4:any = ((this.parent.context.results == (null as any))? (null as any): ((this.parent.context.results.PagedArtists == (null as any))? (null as any): this.parent.context.results.PagedArtists.Artists));
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgFor_6_6.ngForOf = currVal_4;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_4,currVal_4);
      this._expr_4 = currVal_4;
    }
    if ((changes !== (null as any))) { this._NgFor_6_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_6_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  dirtyParentQueriesInternal():void {
    (<_View_SearchComponent0>this.parent)._query_TabComponent_25_0.setDirty();
  }
  private _handle_select_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.parent.context.artistTabActive = true)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_SearchComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_SearchComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_SearchComponent2 extends import1.AppView<any> {
  _el_0:any;
  _el_1:any;
  _text_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SearchComponent2,renderType_SearchComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'p',(null as any));
    this._el_1 = this.renderer.createElement(this._el_0,'em',(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'No artists',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_SearchComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_SearchComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_SearchComponent3 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ArtistListItemComponent_0_4:import32.ArtistListItemComponent;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SearchComponent3,renderType_SearchComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'artist-list-item',(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import33.viewFactory_ArtistListItemComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ArtistListItemComponent_0_4 = new import32.ArtistListItemComponent();
    this._appEl_0.initComponent(this._ArtistListItemComponent_0_4,[],compView_0);
    compView_0.create(this._ArtistListItemComponent_0_4,[],(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import32.ArtistListItemComponent) && (0 === requestNodeIndex))) { return this._ArtistListItemComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.$implicit;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._ArtistListItemComponent_0_4.artist = currVal_0;
      this._expr_0 = currVal_0;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SearchComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_SearchComponent3(viewUtils,parentInjector,declarationEl);
}
class _View_SearchComponent4 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _TabComponent_0_4:import28.TabComponent;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import18.NgIf;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _anchor_6:any;
  /*private*/ _appEl_6:import2.AppElement;
  _TemplateRef_6_5:any;
  _NgFor_6_6:import29.NgFor;
  _text_7:any;
  _text_8:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SearchComponent4,renderType_SearchComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'tab',(null as any));
    this.renderer.setElementAttribute(this._el_0,'heading','Albums');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import30.viewFactory_TabComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._TabComponent_0_4 = new import28.TabComponent();
    this._appEl_0.initComponent(this._TabComponent_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n				',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import26.TemplateRef_(this._appEl_2,viewFactory_SearchComponent5);
    this._NgIf_2_6 = new import18.NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText((null as any),'\n				',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','row');
    this._text_5 = this.renderer.createText(this._el_4,'\n					',(null as any));
    this._anchor_6 = this.renderer.createTemplateAnchor(this._el_4,(null as any));
    this._appEl_6 = new import2.AppElement(6,4,this,this._anchor_6);
    this._TemplateRef_6_5 = new import26.TemplateRef_(this._appEl_6,viewFactory_SearchComponent6);
    this._NgFor_6_6 = new import29.NgFor(this._appEl_6.vcRef,this._TemplateRef_6_5,this.parent.parentInjector.get(import31.IterableDiffers),this.parent.ref);
    this._text_7 = this.renderer.createText(this._el_4,'\n				',(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n			',(null as any));
      compView_0.create(this._TabComponent_0_4,[[].concat([
        this._text_1,
        this._appEl_2,
        this._text_3,
        this._el_4,
        this._text_8
      ]
    )],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'select',this.eventHandler(this._handle_select_0_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    const subscription_0:any = this._TabComponent_0_4.select.subscribe(this.eventHandler(this._handle_select_0_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._anchor_6,
      this._text_7,
      this._text_8
    ]
    ,[disposable_0],[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import26.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import18.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6; }
    if (((token === import26.TemplateRef) && (6 === requestNodeIndex))) { return this._TemplateRef_6_5; }
    if (((token === import29.NgFor) && (6 === requestNodeIndex))) { return this._NgFor_6_6; }
    if (((token === import28.TabComponent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._TabComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_1:any = 'Albums';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._TabComponent_0_4.heading = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this.parent.context.albumsTabActive;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._TabComponent_0_4.active = currVal_2;
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = (((this.parent.context.results == (null as any))? (null as any): ((this.parent.context.results.PagedAlbums == (null as any))? (null as any): ((this.parent.context.results.PagedAlbums.Albums == (null as any))? (null as any): this.parent.context.results.PagedAlbums.Albums.length))) === 0);
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgIf_2_6.ngIf = currVal_3;
      this._expr_3 = currVal_3;
    }
    changes = (null as any);
    const currVal_4:any = ((this.parent.context.results == (null as any))? (null as any): ((this.parent.context.results.PagedAlbums == (null as any))? (null as any): this.parent.context.results.PagedAlbums.Albums));
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgFor_6_6.ngForOf = currVal_4;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_4,currVal_4);
      this._expr_4 = currVal_4;
    }
    if ((changes !== (null as any))) { this._NgFor_6_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_6_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  dirtyParentQueriesInternal():void {
    (<_View_SearchComponent0>this.parent)._query_TabComponent_25_0.setDirty();
  }
  private _handle_select_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.parent.context.albumsTabActive = true)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_SearchComponent4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_SearchComponent4(viewUtils,parentInjector,declarationEl);
}
class _View_SearchComponent5 extends import1.AppView<any> {
  _el_0:any;
  _el_1:any;
  _text_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SearchComponent5,renderType_SearchComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'p',(null as any));
    this._el_1 = this.renderer.createElement(this._el_0,'em',(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'No albums',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_SearchComponent5(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_SearchComponent5(viewUtils,parentInjector,declarationEl);
}
class _View_SearchComponent6 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _AlbumListItemComponent_0_4:import34.AlbumListItemComponent;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SearchComponent6,renderType_SearchComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'album-list-item',(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import35.viewFactory_AlbumListItemComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._AlbumListItemComponent_0_4 = new import34.AlbumListItemComponent();
    this._appEl_0.initComponent(this._AlbumListItemComponent_0_4,[],compView_0);
    compView_0.create(this._AlbumListItemComponent_0_4,[],(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import34.AlbumListItemComponent) && (0 === requestNodeIndex))) { return this._AlbumListItemComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.$implicit;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._AlbumListItemComponent_0_4.album = currVal_0;
      this._expr_0 = currVal_0;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SearchComponent6(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_SearchComponent6(viewUtils,parentInjector,declarationEl);
}
class _View_SearchComponent7 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _TabComponent_0_4:import28.TabComponent;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import18.NgIf;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _anchor_6:any;
  /*private*/ _appEl_6:import2.AppElement;
  _TemplateRef_6_5:any;
  _NgFor_6_6:import29.NgFor;
  _text_7:any;
  _text_8:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SearchComponent7,renderType_SearchComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'tab',(null as any));
    this.renderer.setElementAttribute(this._el_0,'heading','Tracks');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import30.viewFactory_TabComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._TabComponent_0_4 = new import28.TabComponent();
    this._appEl_0.initComponent(this._TabComponent_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n				',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import26.TemplateRef_(this._appEl_2,viewFactory_SearchComponent8);
    this._NgIf_2_6 = new import18.NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText((null as any),'\n				',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ul',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','list-unstyled');
    this._text_5 = this.renderer.createText(this._el_4,'\n					',(null as any));
    this._anchor_6 = this.renderer.createTemplateAnchor(this._el_4,(null as any));
    this._appEl_6 = new import2.AppElement(6,4,this,this._anchor_6);
    this._TemplateRef_6_5 = new import26.TemplateRef_(this._appEl_6,viewFactory_SearchComponent9);
    this._NgFor_6_6 = new import29.NgFor(this._appEl_6.vcRef,this._TemplateRef_6_5,this.parent.parentInjector.get(import31.IterableDiffers),this.parent.ref);
    this._text_7 = this.renderer.createText(this._el_4,'\n				',(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n			',(null as any));
      compView_0.create(this._TabComponent_0_4,[[].concat([
        this._text_1,
        this._appEl_2,
        this._text_3,
        this._el_4,
        this._text_8
      ]
    )],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'select',this.eventHandler(this._handle_select_0_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    const subscription_0:any = this._TabComponent_0_4.select.subscribe(this.eventHandler(this._handle_select_0_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._anchor_6,
      this._text_7,
      this._text_8
    ]
    ,[disposable_0],[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import26.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import18.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6; }
    if (((token === import26.TemplateRef) && (6 === requestNodeIndex))) { return this._TemplateRef_6_5; }
    if (((token === import29.NgFor) && (6 === requestNodeIndex))) { return this._NgFor_6_6; }
    if (((token === import28.TabComponent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._TabComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_1:any = 'Tracks';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._TabComponent_0_4.heading = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this.parent.context.tracksTabActive;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._TabComponent_0_4.active = currVal_2;
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = (((this.parent.context.results == (null as any))? (null as any): ((this.parent.context.results.PagedTracks == (null as any))? (null as any): ((this.parent.context.results.PagedTracks.Tracks == (null as any))? (null as any): this.parent.context.results.PagedTracks.Tracks.length))) === 0);
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgIf_2_6.ngIf = currVal_3;
      this._expr_3 = currVal_3;
    }
    changes = (null as any);
    const currVal_4:any = ((this.parent.context.results == (null as any))? (null as any): ((this.parent.context.results.PagedTracks == (null as any))? (null as any): this.parent.context.results.PagedTracks.Tracks));
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgFor_6_6.ngForOf = currVal_4;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_4,currVal_4);
      this._expr_4 = currVal_4;
    }
    if ((changes !== (null as any))) { this._NgFor_6_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_6_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  dirtyParentQueriesInternal():void {
    (<_View_SearchComponent0>this.parent)._query_TabComponent_25_0.setDirty();
  }
  private _handle_select_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.parent.context.tracksTabActive = true)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_SearchComponent7(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_SearchComponent7(viewUtils,parentInjector,declarationEl);
}
class _View_SearchComponent8 extends import1.AppView<any> {
  _el_0:any;
  _el_1:any;
  _text_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SearchComponent8,renderType_SearchComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'p',(null as any));
    this._el_1 = this.renderer.createElement(this._el_0,'em',(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'No tracks',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_SearchComponent8(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_SearchComponent8(viewUtils,parentInjector,declarationEl);
}
class _View_SearchComponent9 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TrackListItemComponent_2_4:import36.TrackListItemComponent;
  _text_3:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SearchComponent9,renderType_SearchComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'li',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n						',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'track-list-item',(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import37.viewFactory_TrackListItemComponent0(this.viewUtils,this.injector(2),this._appEl_2);
    this._TrackListItemComponent_2_4 = new import36.TrackListItemComponent(this.parent.parent.parentInjector.get(import38.QueueService));
    this._appEl_2.initComponent(this._TrackListItemComponent_2_4,[],compView_2);
    compView_2.create(this._TrackListItemComponent_2_4,[],(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n					',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import36.TrackListItemComponent) && (2 === requestNodeIndex))) { return this._TrackListItemComponent_2_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.$implicit;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._TrackListItemComponent_2_4.track = currVal_0;
      this._expr_0 = currVal_0;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SearchComponent9(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_SearchComponent9(viewUtils,parentInjector,declarationEl);
}