/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../../app/shared/opinion-buttons/opinion-buttons.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from './opinion-buttons.component.css';
import * as import11 from '@angular/common/src/directives/ng_if';
import * as import12 from '@angular/core/src/linker/template_ref';
import * as import13 from '../../../../app/shared/user-list/user-list.component';
import * as import14 from '../user-list/user-list.component.ngfactory';
var renderType_OpinionButtonsComponent_Host:import0.RenderComponentType = (null as any);
class _View_OpinionButtonsComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _OpinionButtonsComponent_0_4:import3.OpinionButtonsComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_OpinionButtonsComponent_Host0,renderType_OpinionButtonsComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('opinion-buttons',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_OpinionButtonsComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._OpinionButtonsComponent_0_4 = new import3.OpinionButtonsComponent();
    this._appEl_0.initComponent(this._OpinionButtonsComponent_0_4,[],compView_0);
    compView_0.create(this._OpinionButtonsComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.OpinionButtonsComponent) && (0 === requestNodeIndex))) { return this._OpinionButtonsComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._OpinionButtonsComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_OpinionButtonsComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_OpinionButtonsComponent_Host === (null as any))) { (renderType_OpinionButtonsComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_OpinionButtonsComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const OpinionButtonsComponentNgFactory:import9.ComponentFactory<import3.OpinionButtonsComponent> = new import9.ComponentFactory<import3.OpinionButtonsComponent>('opinion-buttons',viewFactory_OpinionButtonsComponent_Host0,import3.OpinionButtonsComponent);
const styles_OpinionButtonsComponent:any[] = [import10.styles];
var renderType_OpinionButtonsComponent:import0.RenderComponentType = (null as any);
class _View_OpinionButtonsComponent0 extends import1.AppView<import3.OpinionButtonsComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _anchor_7:any;
  /*private*/ _appEl_7:import2.AppElement;
  _TemplateRef_7_5:any;
  _NgIf_7_6:import11.NgIf;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _anchor_17:any;
  /*private*/ _appEl_17:import2.AppElement;
  _TemplateRef_17_5:any;
  _NgIf_17_6:import11.NgIf;
  _text_18:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_OpinionButtonsComponent0,renderType_OpinionButtonsComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','btn btn-like user-list-container');
    this.renderer.setElementAttribute(this._el_0,'title','Like');
    this._text_1 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'i',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','icon-heart');
    this._text_3 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_4 = this.renderer.createElement(this._el_0,'span',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','badge badge-like');
    this._text_5 = this.renderer.createText(this._el_4,'',(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._anchor_7 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_7 = new import2.AppElement(7,0,this,this._anchor_7);
    this._TemplateRef_7_5 = new import12.TemplateRef_(this._appEl_7,viewFactory_OpinionButtonsComponent1);
    this._NgIf_7_6 = new import11.NgIf(this._appEl_7.vcRef,this._TemplateRef_7_5);
    this._text_8 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_9 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_10 = this.renderer.createElement(parentRenderNode,'button',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','btn btn-veto user-list-container');
    this.renderer.setElementAttribute(this._el_10,'title','Veto');
    this._text_11 = this.renderer.createText(this._el_10,'\n	',(null as any));
    this._el_12 = this.renderer.createElement(this._el_10,'i',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','icon-heart-broken');
    this._text_13 = this.renderer.createText(this._el_10,'\n	',(null as any));
    this._el_14 = this.renderer.createElement(this._el_10,'span',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','badge badge-veto');
    this._text_15 = this.renderer.createText(this._el_14,'',(null as any));
    this._text_16 = this.renderer.createText(this._el_10,'\n	',(null as any));
    this._anchor_17 = this.renderer.createTemplateAnchor(this._el_10,(null as any));
    this._appEl_17 = new import2.AppElement(17,10,this,this._anchor_17);
    this._TemplateRef_17_5 = new import12.TemplateRef_(this._appEl_17,viewFactory_OpinionButtonsComponent2);
    this._NgIf_17_6 = new import11.NgIf(this._appEl_17.vcRef,this._TemplateRef_17_5);
    this._text_18 = this.renderer.createText(this._el_10,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_10,'click',this.eventHandler(this._handle_click_10_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._anchor_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._anchor_17,
      this._text_18
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.TemplateRef) && (7 === requestNodeIndex))) { return this._TemplateRef_7_5; }
    if (((token === import11.NgIf) && (7 === requestNodeIndex))) { return this._NgIf_7_6; }
    if (((token === import12.TemplateRef) && (17 === requestNodeIndex))) { return this._TemplateRef_17_5; }
    if (((token === import11.NgIf) && (17 === requestNodeIndex))) { return this._NgIf_17_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = ((this.context.track == (null as any))? (null as any): this.context.track.LikeCount);
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgIf_7_6.ngIf = currVal_2;
      this._expr_2 = currVal_2;
    }
    const currVal_5:any = ((this.context.track == (null as any))? (null as any): this.context.track.VetoCount);
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._NgIf_17_6.ngIf = currVal_5;
      this._expr_5 = currVal_5;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = import4.interpolate(1,'',((this.context.track == (null as any))? (null as any): this.context.track.LikeCount),'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_5,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = import4.interpolate(1,'',((this.context.track == (null as any))? (null as any): this.context.track.VetoCount),'');
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_15,currVal_4);
      this._expr_4 = currVal_4;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.likeTrack(this.context.track)) !== false);
    return (true && pd_0);
  }
  private _handle_click_10_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.vetoTrack(this.context.track)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_OpinionButtonsComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.OpinionButtonsComponent> {
  if ((renderType_OpinionButtonsComponent === (null as any))) { (renderType_OpinionButtonsComponent = viewUtils.createRenderComponentType('C:/data/solutions/PlayMeExtension/src/app/shared/opinion-buttons/opinion-buttons.component.html',0,import8.ViewEncapsulation.None,styles_OpinionButtonsComponent,{})); }
  return new _View_OpinionButtonsComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_OpinionButtonsComponent1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _UserListComponent_0_4:import13.UserListComponent;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_OpinionButtonsComponent1,renderType_OpinionButtonsComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'user-list',(null as any));
    this.renderer.setElementAttribute(this._el_0,'title','Likes');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import14.viewFactory_UserListComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._UserListComponent_0_4 = new import13.UserListComponent();
    this._appEl_0.initComponent(this._UserListComponent_0_4,[],compView_0);
    compView_0.create(this._UserListComponent_0_4,[],(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.UserListComponent) && (0 === requestNodeIndex))) { return this._UserListComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = ((this.parent.context.track == (null as any))? (null as any): this.parent.context.track.Likes);
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._UserListComponent_0_4.opinions = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = 'Likes';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._UserListComponent_0_4.title = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_OpinionButtonsComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_OpinionButtonsComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_OpinionButtonsComponent2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _UserListComponent_0_4:import13.UserListComponent;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_OpinionButtonsComponent2,renderType_OpinionButtonsComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'user-list',(null as any));
    this.renderer.setElementAttribute(this._el_0,'title','Vetoes');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import14.viewFactory_UserListComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._UserListComponent_0_4 = new import13.UserListComponent();
    this._appEl_0.initComponent(this._UserListComponent_0_4,[],compView_0);
    compView_0.create(this._UserListComponent_0_4,[],(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.UserListComponent) && (0 === requestNodeIndex))) { return this._UserListComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = ((this.parent.context.track == (null as any))? (null as any): this.parent.context.track.Vetoes);
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._UserListComponent_0_4.opinions = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = 'Vetoes';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._UserListComponent_0_4.title = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_OpinionButtonsComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_OpinionButtonsComponent2(viewUtils,parentInjector,declarationEl);
}