/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['.track-comment[_ngcontent-%COMP%]{\r\n	margin-top: 10px;\r\n}'];