/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../app/now-playing/now-playing.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../../app/api/search.service';
import * as import9 from '../../../app/api/audio-zone.service';
import * as import10 from '../../../app/api/user-info.service';
import * as import11 from '../../../app/api/signalr.service';
import * as import12 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import13 from '@angular/core/src/metadata/view';
import * as import14 from '@angular/core/src/linker/component_factory';
import * as import15 from './now-playing.component.css.shim';
import * as import16 from '../../../app/now-playing/zone-selector/zone-selector.component';
import * as import17 from '../../../app/shared/search-bar/search-bar.component';
import * as import18 from '@angular/common/src/directives/ng_if';
import * as import19 from '../../../app/shared/opinion-buttons/opinion-buttons.component';
import * as import20 from '../../../app/shared/tabset/tabset.component';
import * as import21 from '@angular/core/src/linker/query_list';
import * as import22 from '../../../app/shared/tabset/tab/tab.component';
import * as import23 from '@angular/common/src/directives/ng_for';
import * as import24 from '@angular/router/src/directives/router_link';
import * as import25 from './zone-selector/zone-selector.component.ngfactory';
import * as import26 from '../shared/search-bar/search-bar.component.ngfactory';
import * as import27 from '@angular/router/src/router';
import * as import28 from '@angular/core/src/linker/template_ref';
import * as import29 from '../shared/opinion-buttons/opinion-buttons.component.ngfactory';
import * as import30 from '../shared/tabset/tabset.component.ngfactory';
import * as import31 from '../shared/tabset/tab/tab.component.ngfactory';
import * as import32 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import33 from '@angular/router/src/router_state';
import * as import34 from '@angular/common/src/location/location_strategy';
import * as import35 from '@angular/core/src/security';
import * as import36 from '@angular/common/src/pipes/async_pipe';
import * as import37 from '../../../app/shared/queued-track/queued-track.component';
import * as import38 from '../shared/queued-track/queued-track.component.ngfactory';
import * as import39 from '../../../app/api/queue.service';
var renderType_NowPlayingComponent_Host:import0.RenderComponentType = (null as any);
class _View_NowPlayingComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _NowPlayingComponent_0_4:import3.NowPlayingComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_NowPlayingComponent_Host0,renderType_NowPlayingComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('now-playing',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_NowPlayingComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._NowPlayingComponent_0_4 = new import3.NowPlayingComponent(this.parentInjector.get(import8.SearchService),this.parentInjector.get(import9.AudioZoneService),this.parentInjector.get(import10.UserInfoService),this.parentInjector.get(import11.SignalRService),this.parentInjector.get(import12.DomSanitizer));
    this._appEl_0.initComponent(this._NowPlayingComponent_0_4,[],compView_0);
    compView_0.create(this._NowPlayingComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.NowPlayingComponent) && (0 === requestNodeIndex))) { return this._NowPlayingComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._NowPlayingComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NowPlayingComponent_0_4.ngOnDestroy();
  }
}
function viewFactory_NowPlayingComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_NowPlayingComponent_Host === (null as any))) { (renderType_NowPlayingComponent_Host = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,[],{})); }
  return new _View_NowPlayingComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const NowPlayingComponentNgFactory:import14.ComponentFactory<import3.NowPlayingComponent> = new import14.ComponentFactory<import3.NowPlayingComponent>('now-playing',viewFactory_NowPlayingComponent_Host0,import3.NowPlayingComponent);
const styles_NowPlayingComponent:any[] = [import15.styles];
var renderType_NowPlayingComponent:import0.RenderComponentType = (null as any);
class _View_NowPlayingComponent0 extends import1.AppView<import3.NowPlayingComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _ZoneSelectorComponent_9_4:import16.ZoneSelectorComponent;
  _text_10:any;
  _el_11:any;
  /*private*/ _appEl_11:import2.AppElement;
  _SearchBarComponent_11_4:import17.SearchBarComponent;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _el_21:any;
  _text_22:any;
  _anchor_23:any;
  /*private*/ _appEl_23:import2.AppElement;
  _TemplateRef_23_5:any;
  _NgIf_23_6:import18.NgIf;
  _text_24:any;
  _anchor_25:any;
  /*private*/ _appEl_25:import2.AppElement;
  _TemplateRef_25_5:any;
  _NgIf_25_6:import18.NgIf;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _el_29:any;
  _text_30:any;
  _text_31:any;
  _anchor_32:any;
  /*private*/ _appEl_32:import2.AppElement;
  _TemplateRef_32_5:any;
  _NgIf_32_6:import18.NgIf;
  _text_33:any;
  _anchor_34:any;
  /*private*/ _appEl_34:import2.AppElement;
  _TemplateRef_34_5:any;
  _NgIf_34_6:import18.NgIf;
  _text_35:any;
  _el_36:any;
  /*private*/ _appEl_36:import2.AppElement;
  _OpinionButtonsComponent_36_4:import19.OpinionButtonsComponent;
  _text_37:any;
  _anchor_38:any;
  /*private*/ _appEl_38:import2.AppElement;
  _TemplateRef_38_5:any;
  _NgIf_38_6:import18.NgIf;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _text_45:any;
  _text_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  _el_54:any;
  _text_55:any;
  _el_56:any;
  /*private*/ _appEl_56:import2.AppElement;
  _TabsetComponent_56_4:import20.TabsetComponent;
  _query_TabComponent_56_0:import21.QueryList<any>;
  _text_57:any;
  _el_58:any;
  /*private*/ _appEl_58:import2.AppElement;
  _TabComponent_58_4:import22.TabComponent;
  _text_59:any;
  _anchor_60:any;
  /*private*/ _appEl_60:import2.AppElement;
  _TemplateRef_60_5:any;
  _NgIf_60_6:import18.NgIf;
  _text_61:any;
  _anchor_62:any;
  /*private*/ _appEl_62:import2.AppElement;
  _TemplateRef_62_5:any;
  _NgFor_62_6:import23.NgFor;
  _text_63:any;
  _anchor_64:any;
  /*private*/ _appEl_64:import2.AppElement;
  _TemplateRef_64_5:any;
  _NgIf_64_6:import18.NgIf;
  _text_65:any;
  _text_66:any;
  _el_67:any;
  /*private*/ _appEl_67:import2.AppElement;
  _TabComponent_67_4:import22.TabComponent;
  _text_68:any;
  _anchor_69:any;
  /*private*/ _appEl_69:import2.AppElement;
  _TemplateRef_69_5:any;
  _NgFor_69_6:import23.NgFor;
  _text_70:any;
  _el_71:any;
  _RouterLinkWithHref_71_3:import24.RouterLinkWithHref;
  _text_72:any;
  _text_73:any;
  _text_74:any;
  _text_75:any;
  _text_76:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  _arr_0:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_NowPlayingComponent0,renderType_NowPlayingComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','app-root');
    this._text_1 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','album-art-background');
    this._el_3 = this.renderer.createElement(this._el_2,'img',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','content-top');
    this._text_6 = this.renderer.createText(this._el_5,'\n		',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'div',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','row nav-bar');
    this._text_8 = this.renderer.createText(this._el_7,'\n			',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'zone-selector',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','col-xs-3');
    this._appEl_9 = new import2.AppElement(9,7,this,this._el_9);
    var compView_9:any = import25.viewFactory_ZoneSelectorComponent0(this.viewUtils,this.injector(9),this._appEl_9);
    this._ZoneSelectorComponent_9_4 = new import16.ZoneSelectorComponent(this.parentInjector.get(import9.AudioZoneService));
    this._appEl_9.initComponent(this._ZoneSelectorComponent_9_4,[],compView_9);
    compView_9.create(this._ZoneSelectorComponent_9_4,[],(null as any));
    this._text_10 = this.renderer.createText(this._el_7,'\n			',(null as any));
    this._el_11 = this.renderer.createElement(this._el_7,'search-bar',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','col-xs-9');
    this._appEl_11 = new import2.AppElement(11,7,this,this._el_11);
    var compView_11:any = import26.viewFactory_SearchBarComponent0(this.viewUtils,this.injector(11),this._appEl_11);
    this._SearchBarComponent_11_4 = new import17.SearchBarComponent(this.parentInjector.get(import27.Router));
    this._appEl_11.initComponent(this._SearchBarComponent_11_4,[],compView_11);
    compView_11.create(this._SearchBarComponent_11_4,[],(null as any));
    this._text_12 = this.renderer.createText(this._el_7,'\n		',(null as any));
    this._text_13 = this.renderer.createText(this._el_5,'\n\n		',(null as any));
    this._el_14 = this.renderer.createElement(this._el_5,'div',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','now-playing');
    this._text_15 = this.renderer.createText(this._el_14,'\n			',(null as any));
    this._el_16 = this.renderer.createElement(this._el_14,'div',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','row');
    this._text_17 = this.renderer.createText(this._el_16,'\n				',(null as any));
    this._el_18 = this.renderer.createElement(this._el_16,'div',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','col-xs-8');
    this._text_19 = this.renderer.createText(this._el_18,'\n					',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'small',(null as any));
    this._el_21 = this.renderer.createElement(this._el_20,'em',(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'Queued by \n						',(null as any));
    this._anchor_23 = this.renderer.createTemplateAnchor(this._el_21,(null as any));
    this._appEl_23 = new import2.AppElement(23,21,this,this._anchor_23);
    this._TemplateRef_23_5 = new import28.TemplateRef_(this._appEl_23,viewFactory_NowPlayingComponent1);
    this._NgIf_23_6 = new import18.NgIf(this._appEl_23.vcRef,this._TemplateRef_23_5);
    this._text_24 = this.renderer.createText(this._el_21,'\n						',(null as any));
    this._anchor_25 = this.renderer.createTemplateAnchor(this._el_21,(null as any));
    this._appEl_25 = new import2.AppElement(25,21,this,this._anchor_25);
    this._TemplateRef_25_5 = new import28.TemplateRef_(this._appEl_25,viewFactory_NowPlayingComponent2);
    this._NgIf_25_6 = new import18.NgIf(this._appEl_25.vcRef,this._TemplateRef_25_5);
    this._text_26 = this.renderer.createText(this._el_21,'\n						',(null as any));
    this._text_27 = this.renderer.createText(this._el_18,'\n					',(null as any));
    this._el_28 = this.renderer.createElement(this._el_18,'h1',(null as any));
    this._el_29 = this.renderer.createElement(this._el_28,'a',(null as any));
    this.renderer.setElementAttribute(this._el_29,'target','_blank');
    this.renderer.setElementAttribute(this._el_29,'title','Open in spotify');
    this._text_30 = this.renderer.createText(this._el_29,'',(null as any));
    this._text_31 = this.renderer.createText(this._el_18,'\n\n					',(null as any));
    this._anchor_32 = this.renderer.createTemplateAnchor(this._el_18,(null as any));
    this._appEl_32 = new import2.AppElement(32,18,this,this._anchor_32);
    this._TemplateRef_32_5 = new import28.TemplateRef_(this._appEl_32,viewFactory_NowPlayingComponent3);
    this._NgIf_32_6 = new import18.NgIf(this._appEl_32.vcRef,this._TemplateRef_32_5);
    this._text_33 = this.renderer.createText(this._el_18,'\n					',(null as any));
    this._anchor_34 = this.renderer.createTemplateAnchor(this._el_18,(null as any));
    this._appEl_34 = new import2.AppElement(34,18,this,this._anchor_34);
    this._TemplateRef_34_5 = new import28.TemplateRef_(this._appEl_34,viewFactory_NowPlayingComponent5);
    this._NgIf_34_6 = new import18.NgIf(this._appEl_34.vcRef,this._TemplateRef_34_5);
    this._text_35 = this.renderer.createText(this._el_18,'\n					',(null as any));
    this._el_36 = this.renderer.createElement(this._el_18,'opinion-buttons',(null as any));
    this._appEl_36 = new import2.AppElement(36,18,this,this._el_36);
    var compView_36:any = import29.viewFactory_OpinionButtonsComponent0(this.viewUtils,this.injector(36),this._appEl_36);
    this._OpinionButtonsComponent_36_4 = new import19.OpinionButtonsComponent();
    this._appEl_36.initComponent(this._OpinionButtonsComponent_36_4,[],compView_36);
    compView_36.create(this._OpinionButtonsComponent_36_4,[],(null as any));
    this._text_37 = this.renderer.createText(this._el_18,'\n					',(null as any));
    this._anchor_38 = this.renderer.createTemplateAnchor(this._el_18,(null as any));
    this._appEl_38 = new import2.AppElement(38,18,this,this._anchor_38);
    this._TemplateRef_38_5 = new import28.TemplateRef_(this._appEl_38,viewFactory_NowPlayingComponent6);
    this._NgIf_38_6 = new import18.NgIf(this._appEl_38.vcRef,this._TemplateRef_38_5);
    this._text_39 = this.renderer.createText(this._el_18,'\n				',(null as any));
    this._text_40 = this.renderer.createText(this._el_16,'\n				',(null as any));
    this._el_41 = this.renderer.createElement(this._el_16,'div',(null as any));
    this.renderer.setElementAttribute(this._el_41,'class','col-xs-4');
    this._text_42 = this.renderer.createText(this._el_41,'\n					',(null as any));
    this._el_43 = this.renderer.createElement(this._el_41,'img',(null as any));
    this.renderer.setElementAttribute(this._el_43,'class','img-responsive');
    this._text_44 = this.renderer.createText(this._el_41,'\n				',(null as any));
    this._text_45 = this.renderer.createText(this._el_16,'\n			',(null as any));
    this._text_46 = this.renderer.createText(this._el_14,'\n		',(null as any));
    this._text_47 = this.renderer.createText(this._el_5,'\n		',(null as any));
    this._el_48 = this.renderer.createElement(this._el_5,'div',(null as any));
    this.renderer.setElementAttribute(this._el_48,'class','progress now-playing-progress');
    this._text_49 = this.renderer.createText(this._el_48,'\n			',(null as any));
    this._el_50 = this.renderer.createElement(this._el_48,'div',(null as any));
    this.renderer.setElementAttribute(this._el_50,'class','progress-bar');
    this._text_51 = this.renderer.createText(this._el_48,'\n		',(null as any));
    this._text_52 = this.renderer.createText(this._el_5,'\n	',(null as any));
    this._text_53 = this.renderer.createText(this._el_0,'\n\n	',(null as any));
    this._el_54 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_54,'class','content-bottom');
    this._text_55 = this.renderer.createText(this._el_54,'\n		',(null as any));
    this._el_56 = this.renderer.createElement(this._el_54,'tabset',(null as any));
    this._appEl_56 = new import2.AppElement(56,54,this,this._el_56);
    var compView_56:any = import30.viewFactory_TabsetComponent0(this.viewUtils,this.injector(56),this._appEl_56);
    this._TabsetComponent_56_4 = new import20.TabsetComponent();
    this._query_TabComponent_56_0 = new import21.QueryList<any>();
    this._appEl_56.initComponent(this._TabsetComponent_56_4,[],compView_56);
    this._text_57 = this.renderer.createText((null as any),'\n			',(null as any));
    this._el_58 = this.renderer.createElement((null as any),'tab',(null as any));
    this.renderer.setElementAttribute(this._el_58,'heading','Next up');
    this._appEl_58 = new import2.AppElement(58,56,this,this._el_58);
    var compView_58:any = import31.viewFactory_TabComponent0(this.viewUtils,this.injector(58),this._appEl_58);
    this._TabComponent_58_4 = new import22.TabComponent();
    this._appEl_58.initComponent(this._TabComponent_58_4,[],compView_58);
    this._text_59 = this.renderer.createText((null as any),'\n				',(null as any));
    this._anchor_60 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_60 = new import2.AppElement(60,58,this,this._anchor_60);
    this._TemplateRef_60_5 = new import28.TemplateRef_(this._appEl_60,viewFactory_NowPlayingComponent7);
    this._NgIf_60_6 = new import18.NgIf(this._appEl_60.vcRef,this._TemplateRef_60_5);
    this._text_61 = this.renderer.createText((null as any),'\n				',(null as any));
    this._anchor_62 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_62 = new import2.AppElement(62,58,this,this._anchor_62);
    this._TemplateRef_62_5 = new import28.TemplateRef_(this._appEl_62,viewFactory_NowPlayingComponent8);
    this._NgFor_62_6 = new import23.NgFor(this._appEl_62.vcRef,this._TemplateRef_62_5,this.parentInjector.get(import32.IterableDiffers),this.ref);
    this._text_63 = this.renderer.createText((null as any),'\n\n				',(null as any));
    this._anchor_64 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_64 = new import2.AppElement(64,58,this,this._anchor_64);
    this._TemplateRef_64_5 = new import28.TemplateRef_(this._appEl_64,viewFactory_NowPlayingComponent9);
    this._NgIf_64_6 = new import18.NgIf(this._appEl_64.vcRef,this._TemplateRef_64_5);
    this._text_65 = this.renderer.createText((null as any),'\n			',(null as any));
      compView_58.create(this._TabComponent_58_4,[[].concat([
        this._text_59,
        this._appEl_60,
        this._text_61,
        this._appEl_62,
        this._text_63,
        this._appEl_64,
        this._text_65
      ]
    )],(null as any));
    this._text_66 = this.renderer.createText((null as any),'\n			',(null as any));
    this._el_67 = this.renderer.createElement((null as any),'tab',(null as any));
    this.renderer.setElementAttribute(this._el_67,'heading','History');
    this._appEl_67 = new import2.AppElement(67,56,this,this._el_67);
    var compView_67:any = import31.viewFactory_TabComponent0(this.viewUtils,this.injector(67),this._appEl_67);
    this._TabComponent_67_4 = new import22.TabComponent();
    this._appEl_67.initComponent(this._TabComponent_67_4,[],compView_67);
    this._text_68 = this.renderer.createText((null as any),'\n				',(null as any));
    this._anchor_69 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_69 = new import2.AppElement(69,67,this,this._anchor_69);
    this._TemplateRef_69_5 = new import28.TemplateRef_(this._appEl_69,viewFactory_NowPlayingComponent10);
    this._NgFor_69_6 = new import23.NgFor(this._appEl_69.vcRef,this._TemplateRef_69_5,this.parentInjector.get(import32.IterableDiffers),this.ref);
    this._text_70 = this.renderer.createText((null as any),'\n				\n				',(null as any));
    this._el_71 = this.renderer.createElement((null as any),'a',(null as any));
    this._RouterLinkWithHref_71_3 = new import24.RouterLinkWithHref(this.parentInjector.get(import27.Router),this.parentInjector.get(import33.ActivatedRoute),this.parentInjector.get(import34.LocationStrategy));
    this._text_72 = this.renderer.createText(this._el_71,'See all history',(null as any));
    this._text_73 = this.renderer.createText((null as any),'\n			',(null as any));
      compView_67.create(this._TabComponent_67_4,[[].concat([
        this._text_68,
        this._appEl_69,
        this._text_70,
        this._el_71,
        this._text_73
      ]
    )],(null as any));
    this._text_74 = this.renderer.createText((null as any),'\n		',(null as any));
      compView_56.create(this._TabsetComponent_56_4,[[].concat([
        this._text_57,
        this._el_58,
        this._text_66,
        this._el_67,
        this._text_74
      ]
    )],(null as any));
    this._text_75 = this.renderer.createText(this._el_54,'\n	',(null as any));
    this._text_76 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_9,'zoneChanged',this.eventHandler(this._handle_zoneChanged_9_0.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    const subscription_0:any = this._ZoneSelectorComponent_9_4.zoneChanged.subscribe(this.eventHandler(this._handle_zoneChanged_9_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_36,'like',this.eventHandler(this._handle_like_36_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_36,'veto',this.eventHandler(this._handle_veto_36_1.bind(this)));
    this._expr_11 = import7.UNINITIALIZED;
    const subscription_1:any = this._OpinionButtonsComponent_36_4.veto.subscribe(this.eventHandler(this._handle_veto_36_1.bind(this)));
    const subscription_2:any = this._OpinionButtonsComponent_36_4.like.subscribe(this.eventHandler(this._handle_like_36_0.bind(this)));
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_71,'click',this.eventHandler(this._handle_click_71_0.bind(this)));
    this._arr_0 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._el_21,
      this._text_22,
      this._anchor_23,
      this._text_24,
      this._anchor_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._anchor_32,
      this._text_33,
      this._anchor_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._anchor_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._text_45,
      this._text_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._anchor_60,
      this._text_61,
      this._anchor_62,
      this._text_63,
      this._anchor_64,
      this._text_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._anchor_69,
      this._text_70,
      this._el_71,
      this._text_72,
      this._text_73,
      this._text_74,
      this._text_75,
      this._text_76
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import16.ZoneSelectorComponent) && (9 === requestNodeIndex))) { return this._ZoneSelectorComponent_9_4; }
    if (((token === import17.SearchBarComponent) && (11 === requestNodeIndex))) { return this._SearchBarComponent_11_4; }
    if (((token === import28.TemplateRef) && (23 === requestNodeIndex))) { return this._TemplateRef_23_5; }
    if (((token === import18.NgIf) && (23 === requestNodeIndex))) { return this._NgIf_23_6; }
    if (((token === import28.TemplateRef) && (25 === requestNodeIndex))) { return this._TemplateRef_25_5; }
    if (((token === import18.NgIf) && (25 === requestNodeIndex))) { return this._NgIf_25_6; }
    if (((token === import28.TemplateRef) && (32 === requestNodeIndex))) { return this._TemplateRef_32_5; }
    if (((token === import18.NgIf) && (32 === requestNodeIndex))) { return this._NgIf_32_6; }
    if (((token === import28.TemplateRef) && (34 === requestNodeIndex))) { return this._TemplateRef_34_5; }
    if (((token === import18.NgIf) && (34 === requestNodeIndex))) { return this._NgIf_34_6; }
    if (((token === import19.OpinionButtonsComponent) && (36 === requestNodeIndex))) { return this._OpinionButtonsComponent_36_4; }
    if (((token === import28.TemplateRef) && (38 === requestNodeIndex))) { return this._TemplateRef_38_5; }
    if (((token === import18.NgIf) && (38 === requestNodeIndex))) { return this._NgIf_38_6; }
    if (((token === import28.TemplateRef) && (60 === requestNodeIndex))) { return this._TemplateRef_60_5; }
    if (((token === import18.NgIf) && (60 === requestNodeIndex))) { return this._NgIf_60_6; }
    if (((token === import28.TemplateRef) && (62 === requestNodeIndex))) { return this._TemplateRef_62_5; }
    if (((token === import23.NgFor) && (62 === requestNodeIndex))) { return this._NgFor_62_6; }
    if (((token === import28.TemplateRef) && (64 === requestNodeIndex))) { return this._TemplateRef_64_5; }
    if (((token === import18.NgIf) && (64 === requestNodeIndex))) { return this._NgIf_64_6; }
    if (((token === import22.TabComponent) && ((58 <= requestNodeIndex) && (requestNodeIndex <= 65)))) { return this._TabComponent_58_4; }
    if (((token === import28.TemplateRef) && (69 === requestNodeIndex))) { return this._TemplateRef_69_5; }
    if (((token === import23.NgFor) && (69 === requestNodeIndex))) { return this._NgFor_69_6; }
    if (((token === import24.RouterLinkWithHref) && ((71 <= requestNodeIndex) && (requestNodeIndex <= 72)))) { return this._RouterLinkWithHref_71_3; }
    if (((token === import22.TabComponent) && ((67 <= requestNodeIndex) && (requestNodeIndex <= 73)))) { return this._TabComponent_67_4; }
    if (((token === import20.TabsetComponent) && ((56 <= requestNodeIndex) && (requestNodeIndex <= 74)))) { return this._TabsetComponent_56_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_2:any = this.context.activeZone;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._ZoneSelectorComponent_9_4.activeZone = currVal_2;
      this._expr_2 = currVal_2;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ZoneSelectorComponent_9_4.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._SearchBarComponent_11_4.ngOnInit(); }
    const currVal_3:any = ((this.context.currentTrack == (null as any))? (null as any): this.context.currentTrack.url);
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgIf_23_6.ngIf = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_4:boolean = !((this.context.currentTrack == (null as any))? (null as any): this.context.currentTrack.url);
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgIf_25_6.ngIf = currVal_4;
      this._expr_4 = currVal_4;
    }
    const currVal_7:any = ((this.context.currentTrack == (null as any))? (null as any): ((this.context.currentTrack.Track == (null as any))? (null as any): ((this.context.currentTrack.Track.Artists == (null as any))? (null as any): this.context.currentTrack.Track.Artists.length)));
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._NgIf_32_6.ngIf = currVal_7;
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = ((this.context.currentTrack == (null as any))? (null as any): ((this.context.currentTrack.Track == (null as any))? (null as any): this.context.currentTrack.Track.Album));
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._NgIf_34_6.ngIf = currVal_8;
      this._expr_8 = currVal_8;
    }
    const currVal_11:any = this.context.currentTrack;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._OpinionButtonsComponent_36_4.track = currVal_11;
      this._expr_11 = currVal_11;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._OpinionButtonsComponent_36_4.ngOnInit(); }
    const currVal_12:any = ((this.context.currentTrack == (null as any))? (null as any): this.context.currentTrack.Reason);
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._NgIf_38_6.ngIf = currVal_12;
      this._expr_12 = currVal_12;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TabsetComponent_56_4.ngOnInit(); }
    const currVal_16:any = 'Next up';
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this._TabComponent_58_4.heading = currVal_16;
      this._expr_16 = currVal_16;
    }
    const currVal_17:boolean = !((this.context.trackQueue == (null as any))? (null as any): this.context.trackQueue.length);
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this._NgIf_60_6.ngIf = currVal_17;
      this._expr_17 = currVal_17;
    }
    changes = (null as any);
    const currVal_18:any = this.context.trackQueue;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this._NgFor_62_6.ngForOf = currVal_18;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_18,currVal_18);
      this._expr_18 = currVal_18;
    }
    if ((changes !== (null as any))) { this._NgFor_62_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_62_6.ngDoCheck(); }
    const currVal_19:any = ((this.context.trackQueue == (null as any))? (null as any): this.context.trackQueue.length);
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this._NgIf_64_6.ngIf = currVal_19;
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = 'History';
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this._TabComponent_67_4.heading = currVal_20;
      this._expr_20 = currVal_20;
    }
    changes = (null as any);
    const currVal_21:any = this.context.trackHistory;
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this._NgFor_69_6.ngForOf = currVal_21;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_21,currVal_21);
      this._expr_21 = currVal_21;
    }
    if ((changes !== (null as any))) { this._NgFor_69_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_69_6.ngDoCheck(); }
    changes = (null as any);
    const currVal_23:any = this._arr_0('/history');
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this._RouterLinkWithHref_71_3.routerLink = currVal_23;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_23,currVal_23);
      this._expr_23 = currVal_23;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_71_3.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_TabComponent_56_0.dirty) {
        this._query_TabComponent_56_0.reset([
          this._TabComponent_58_4,
          this._TabComponent_67_4
        ]
        );
        this._TabsetComponent_56_4.tabs = this._query_TabComponent_56_0;
        this._query_TabComponent_56_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._TabsetComponent_56_4.ngAfterContentInit(); }
    }
    const currVal_0:any = (((this.context.currentTrack == (null as any))? (null as any): ((this.context.currentTrack.Track == (null as any))? (null as any): ((this.context.currentTrack.Track.Album == (null as any))? (null as any): this.context.currentTrack.Track.Album.ArtworkUrlLarge))) || '/assets/images/pixel.gif');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_3,'src',this.viewUtils.sanitizer.sanitize(import35.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    const currVal_5:any = import4.interpolate(1,'',((this.context.currentTrack == (null as any))? (null as any): ((this.context.currentTrack.Track == (null as any))? (null as any): this.context.currentTrack.Track.ExternalLink)),'');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementProperty(this._el_29,'href',this.viewUtils.sanitizer.sanitize(import35.SecurityContext.URL,currVal_5));
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = import4.interpolate(1,'',((this.context.currentTrack == (null as any))? (null as any): ((this.context.currentTrack.Track == (null as any))? (null as any): this.context.currentTrack.Track.Name)),'');
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setText(this._text_30,currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_13:any = (((this.context.currentTrack == (null as any))? (null as any): ((this.context.currentTrack.Track == (null as any))? (null as any): ((this.context.currentTrack.Track.Album == (null as any))? (null as any): this.context.currentTrack.Track.Album.ArtworkUrlLarge))) || '/assets/images/pixel.gif');
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementProperty(this._el_43,'src',this.viewUtils.sanitizer.sanitize(import35.SecurityContext.URL,currVal_13));
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this.context.trackProgress;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementStyle(this._el_50,'width',((this.viewUtils.sanitizer.sanitize(import35.SecurityContext.STYLE,currVal_14) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import35.SecurityContext.STYLE,currVal_14).toString()));
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._TabsetComponent_56_4.clazz;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_56,'tab-container',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_24:any = this._RouterLinkWithHref_71_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementProperty(this._el_71,'href',this.viewUtils.sanitizer.sanitize(import35.SecurityContext.URL,currVal_24));
      this._expr_24 = currVal_24;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_71_3.ngOnDestroy();
  }
  private _handle_zoneChanged_9_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.changeZone($event)) !== false);
    return (true && pd_0);
  }
  private _handle_like_36_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.likeTrack(this.context.currentTrack)) !== false);
    return (true && pd_0);
  }
  private _handle_veto_36_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.vetoTrack(this.context.currentTrack)) !== false);
    return (true && pd_0);
  }
  private _handle_click_71_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_71_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_NowPlayingComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.NowPlayingComponent> {
  if ((renderType_NowPlayingComponent === (null as any))) { (renderType_NowPlayingComponent = viewUtils.createRenderComponentType('C:/data/solutions/PlayMeExtension/src/app/now-playing/now-playing.component.html',0,import13.ViewEncapsulation.Emulated,styles_NowPlayingComponent,{})); }
  return new _View_NowPlayingComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_NowPlayingComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  /*private*/ _expr_0:any;
  _pipe_async_0:import36.AsyncPipe;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_NowPlayingComponent1,renderType_NowPlayingComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'a',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','user-link');
    this.renderer.setElementAttribute(this._el_0,'disabled','');
    this.renderer.setElementAttribute(this._el_0,'target','_blank');
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'img',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._pipe_async_0 = new import36.AsyncPipe(this.parent.ref);
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = ((this.parent.context.currentTrack == (null as any))? (null as any): this.parent.context.currentTrack.url);
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_0,'href',this.viewUtils.sanitizer.sanitize(import35.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    valUnwrapper.reset();
    const currVal_1:any = import4.interpolate(1,'',valUnwrapper.unwrap(this._pipe_async_0.transform(((this.parent.context.currentTrack == (null as any))? (null as any): this.parent.context.currentTrack.fullName))),'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_1,currVal_1))) {
      this.renderer.setText(this._text_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = ((this.parent.context.currentTrack == (null as any))? (null as any): this.parent.context.currentTrack.userPhotoUrl);
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_2,'src',this.viewUtils.sanitizer.sanitize(import35.SecurityContext.URL,currVal_2));
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._pipe_async_0.ngOnDestroy();
  }
}
function viewFactory_NowPlayingComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_NowPlayingComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_NowPlayingComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _pipe_async_0:import36.AsyncPipe;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_NowPlayingComponent2,renderType_NowPlayingComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._pipe_async_0 = new import36.AsyncPipe(this.parent.ref);
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    this.detectContentChildrenChanges(throwOnChange);
    valUnwrapper.reset();
    const currVal_0:any = import4.interpolate(1,'',valUnwrapper.unwrap(this._pipe_async_0.transform(((this.parent.context.currentTrack == (null as any))? (null as any): this.parent.context.currentTrack.fullName))),'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_0,currVal_0))) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._pipe_async_0.ngOnDestroy();
  }
}
function viewFactory_NowPlayingComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_NowPlayingComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_NowPlayingComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgFor_2_6:import23.NgFor;
  _text_3:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_NowPlayingComponent3,renderType_NowPlayingComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ul',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','comma-separated');
    this._text_1 = this.renderer.createText(this._el_0,'\n						',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import28.TemplateRef_(this._appEl_2,viewFactory_NowPlayingComponent4);
    this._NgFor_2_6 = new import23.NgFor(this._appEl_2.vcRef,this._TemplateRef_2_5,this.parent.parentInjector.get(import32.IterableDiffers),this.parent.ref);
    this._text_3 = this.renderer.createText(this._el_0,'\n					',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import28.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import23.NgFor) && (2 === requestNodeIndex))) { return this._NgFor_2_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = ((this.parent.context.currentTrack == (null as any))? (null as any): ((this.parent.context.currentTrack.Track == (null as any))? (null as any): this.parent.context.currentTrack.Track.Artists));
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgFor_2_6.ngForOf = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._NgFor_2_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_2_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_NowPlayingComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_NowPlayingComponent3(viewUtils,parentInjector,declarationEl);
}
class _View_NowPlayingComponent4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _RouterLinkWithHref_2_3:import24.RouterLinkWithHref;
  _text_3:any;
  _text_4:any;
  _arr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_NowPlayingComponent4,renderType_NowPlayingComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'li',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n							',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'a',(null as any));
    this._RouterLinkWithHref_2_3 = new import24.RouterLinkWithHref(this.parent.parent.parentInjector.get(import27.Router),this.parent.parent.parentInjector.get(import33.ActivatedRoute),this.parent.parent.parentInjector.get(import34.LocationStrategy));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n						',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._arr_0 = import4.pureProxy3((p0:any,p1:any,p2:any):any[] => {
      return [
        p0,
        p1,
        p2
      ]
      ;
    });
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.RouterLinkWithHref) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._RouterLinkWithHref_2_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_1:any = this._arr_0('/artist',this.context.$implicit.MusicProvider.Identifier,this.context.$implicit.Link);
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._RouterLinkWithHref_2_3.routerLink = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_2_3.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = this._RouterLinkWithHref_2_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_2,'href',this.viewUtils.sanitizer.sanitize(import35.SecurityContext.URL,currVal_2));
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import4.interpolate(1,'',this.context.$implicit.Name,'');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_2_3.ngOnDestroy();
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_2_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_NowPlayingComponent4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_NowPlayingComponent4(viewUtils,parentInjector,declarationEl);
}
class _View_NowPlayingComponent5 extends import1.AppView<any> {
  _el_0:any;
  _RouterLinkWithHref_0_3:import24.RouterLinkWithHref;
  _text_1:any;
  _arr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_NowPlayingComponent5,renderType_NowPlayingComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'a',(null as any));
    this._RouterLinkWithHref_0_3 = new import24.RouterLinkWithHref(this.parent.parentInjector.get(import27.Router),this.parent.parentInjector.get(import33.ActivatedRoute),this.parent.parentInjector.get(import34.LocationStrategy));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._arr_0 = import4.pureProxy3((p0:any,p1:any,p2:any):any[] => {
      return [
        p0,
        p1,
        p2
      ]
      ;
    });
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.RouterLinkWithHref) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._RouterLinkWithHref_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_1:any = this._arr_0('/album',((this.parent.context.currentTrack == (null as any))? (null as any): ((this.parent.context.currentTrack.Track == (null as any))? (null as any): this.parent.context.currentTrack.Track.Album.MusicProvider.Identifier)),((this.parent.context.currentTrack == (null as any))? (null as any): ((this.parent.context.currentTrack.Track == (null as any))? (null as any): this.parent.context.currentTrack.Track.Album.Link)));
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._RouterLinkWithHref_0_3.routerLink = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_0_3.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = this._RouterLinkWithHref_0_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_0,'href',this.viewUtils.sanitizer.sanitize(import35.SecurityContext.URL,currVal_2));
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import4.interpolate(1,'',((this.parent.context.currentTrack == (null as any))? (null as any): ((this.parent.context.currentTrack.Track == (null as any))? (null as any): ((this.parent.context.currentTrack.Track.Album == (null as any))? (null as any): this.parent.context.currentTrack.Track.Album.Name))),'');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_1,currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_0_3.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_0_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_NowPlayingComponent5(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_NowPlayingComponent5(viewUtils,parentInjector,declarationEl);
}
class _View_NowPlayingComponent6 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_NowPlayingComponent6,renderType_NowPlayingComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'p',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','track-comment');
    this._text_1 = this.renderer.createText(this._el_0,'\n						',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'em',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n					',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',((this.parent.context.currentTrack == (null as any))? (null as any): this.parent.context.currentTrack.Reason),'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_3,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_NowPlayingComponent6(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_NowPlayingComponent6(viewUtils,parentInjector,declarationEl);
}
class _View_NowPlayingComponent7 extends import1.AppView<any> {
  _el_0:any;
  _el_1:any;
  _text_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_NowPlayingComponent7,renderType_NowPlayingComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'p',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','text');
    this._el_1 = this.renderer.createElement(this._el_0,'em',(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'There are no tracks in the queue',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_NowPlayingComponent7(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_NowPlayingComponent7(viewUtils,parentInjector,declarationEl);
}
class _View_NowPlayingComponent8 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _QueuedTrackComponent_0_4:import37.QueuedTrackComponent;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_NowPlayingComponent8,renderType_NowPlayingComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'queued-track',(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import38.viewFactory_QueuedTrackComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._QueuedTrackComponent_0_4 = new import37.QueuedTrackComponent(this.parent.parentInjector.get(import39.QueueService));
    this._appEl_0.initComponent(this._QueuedTrackComponent_0_4,[],compView_0);
    compView_0.create(this._QueuedTrackComponent_0_4,[],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'likeTrack',this.eventHandler(this._handle_likeTrack_0_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_0,'vetoTrack',this.eventHandler(this._handle_vetoTrack_0_1.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    const subscription_0:any = this._QueuedTrackComponent_0_4.likeTrack.subscribe(this.eventHandler(this._handle_likeTrack_0_0.bind(this)));
    const subscription_1:any = this._QueuedTrackComponent_0_4.vetoTrack.subscribe(this.eventHandler(this._handle_vetoTrack_0_1.bind(this)));
    this.init([].concat([this._el_0]),[this._el_0],[
      disposable_0,
      disposable_1
    ]
    ,[
      subscription_0,
      subscription_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import37.QueuedTrackComponent) && (0 === requestNodeIndex))) { return this._QueuedTrackComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = this.context.$implicit;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._QueuedTrackComponent_0_4.queuedTrack = currVal_2;
      this._expr_2 = currVal_2;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._QueuedTrackComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_likeTrack_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.likeTrack(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_vetoTrack_0_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.vetoTrack(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_NowPlayingComponent8(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_NowPlayingComponent8(viewUtils,parentInjector,declarationEl);
}
class _View_NowPlayingComponent9 extends import1.AppView<any> {
  _el_0:any;
  _RouterLinkWithHref_0_3:import24.RouterLinkWithHref;
  _text_1:any;
  _arr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_NowPlayingComponent9,renderType_NowPlayingComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'a',(null as any));
    this._RouterLinkWithHref_0_3 = new import24.RouterLinkWithHref(this.parent.parentInjector.get(import27.Router),this.parent.parentInjector.get(import33.ActivatedRoute),this.parent.parentInjector.get(import34.LocationStrategy));
    this._text_1 = this.renderer.createText(this._el_0,'See all queued tracks',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._arr_0 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.RouterLinkWithHref) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._RouterLinkWithHref_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_1:any = this._arr_0('/queue');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._RouterLinkWithHref_0_3.routerLink = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_0_3.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = this._RouterLinkWithHref_0_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_0,'href',this.viewUtils.sanitizer.sanitize(import35.SecurityContext.URL,currVal_2));
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_0_3.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_0_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_NowPlayingComponent9(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_NowPlayingComponent9(viewUtils,parentInjector,declarationEl);
}
class _View_NowPlayingComponent10 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _QueuedTrackComponent_0_4:import37.QueuedTrackComponent;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_NowPlayingComponent10,renderType_NowPlayingComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'queued-track',(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import38.viewFactory_QueuedTrackComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._QueuedTrackComponent_0_4 = new import37.QueuedTrackComponent(this.parent.parentInjector.get(import39.QueueService));
    this._appEl_0.initComponent(this._QueuedTrackComponent_0_4,[],compView_0);
    compView_0.create(this._QueuedTrackComponent_0_4,[],(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import37.QueuedTrackComponent) && (0 === requestNodeIndex))) { return this._QueuedTrackComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.$implicit;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._QueuedTrackComponent_0_4.queuedTrack = currVal_0;
      this._expr_0 = currVal_0;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._QueuedTrackComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_NowPlayingComponent10(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_NowPlayingComponent10(viewUtils,parentInjector,declarationEl);
}