/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../app/history/history.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../../app/api/queue.service';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from './history.component.css.shim';
import * as import12 from '../../../app/now-playing/zone-selector/zone-selector.component';
import * as import13 from '../../../app/shared/search-bar/search-bar.component';
import * as import14 from '../../../app/shared/breadcrumbs/breadcrumbs.component';
import * as import15 from '../../../app/shared/tabset/tabset.component';
import * as import16 from '@angular/core/src/linker/query_list';
import * as import17 from '../../../app/shared/tabset/tab/tab.component';
import * as import18 from '@angular/common/src/directives/ng_if';
import * as import19 from '@angular/common/src/directives/ng_for';
import * as import20 from '../now-playing/zone-selector/zone-selector.component.ngfactory';
import * as import21 from '../../../app/api/audio-zone.service';
import * as import22 from '../shared/search-bar/search-bar.component.ngfactory';
import * as import23 from '@angular/router/src/router';
import * as import24 from '../shared/breadcrumbs/breadcrumbs.component.ngfactory';
import * as import25 from '@angular/common/src/location/location';
import * as import26 from '../shared/tabset/tabset.component.ngfactory';
import * as import27 from '../shared/tabset/tab/tab.component.ngfactory';
import * as import28 from '@angular/core/src/linker/template_ref';
import * as import29 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import30 from '@angular/core/src/security';
import * as import31 from '../../../app/shared/queued-track/queued-track.component';
import * as import32 from '../shared/queued-track/queued-track.component.ngfactory';
var renderType_HistoryComponent_Host:import0.RenderComponentType = (null as any);
class _View_HistoryComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _HistoryComponent_0_4:import3.HistoryComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HistoryComponent_Host0,renderType_HistoryComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-history',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_HistoryComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HistoryComponent_0_4 = new import3.HistoryComponent(this.parentInjector.get(import8.QueueService));
    this._appEl_0.initComponent(this._HistoryComponent_0_4,[],compView_0);
    compView_0.create(this._HistoryComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.HistoryComponent) && (0 === requestNodeIndex))) { return this._HistoryComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._HistoryComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_HistoryComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_HistoryComponent_Host === (null as any))) { (renderType_HistoryComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_HistoryComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const HistoryComponentNgFactory:import10.ComponentFactory<import3.HistoryComponent> = new import10.ComponentFactory<import3.HistoryComponent>('app-history',viewFactory_HistoryComponent_Host0,import3.HistoryComponent);
const styles_HistoryComponent:any[] = [import11.styles];
var renderType_HistoryComponent:import0.RenderComponentType = (null as any);
class _View_HistoryComponent0 extends import1.AppView<import3.HistoryComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _ZoneSelectorComponent_9_4:import12.ZoneSelectorComponent;
  _text_10:any;
  _el_11:any;
  /*private*/ _appEl_11:import2.AppElement;
  _SearchBarComponent_11_4:import13.SearchBarComponent;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import2.AppElement;
  _BreadcrumbsComponent_14_4:import14.BreadcrumbsComponent;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _el_22:any;
  /*private*/ _appEl_22:import2.AppElement;
  _TabsetComponent_22_4:import15.TabsetComponent;
  _query_TabComponent_22_0:import16.QueryList<any>;
  _text_23:any;
  _el_24:any;
  /*private*/ _appEl_24:import2.AppElement;
  _TabComponent_24_4:import17.TabComponent;
  _text_25:any;
  _anchor_26:any;
  /*private*/ _appEl_26:import2.AppElement;
  _TemplateRef_26_5:any;
  _NgIf_26_6:import18.NgIf;
  _text_27:any;
  _anchor_28:any;
  /*private*/ _appEl_28:import2.AppElement;
  _TemplateRef_28_5:any;
  _NgFor_28_6:import19.NgFor;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  /*private*/ _appEl_31:import2.AppElement;
  _TabComponent_31_4:import17.TabComponent;
  _text_32:any;
  _anchor_33:any;
  /*private*/ _appEl_33:import2.AppElement;
  _TemplateRef_33_5:any;
  _NgIf_33_6:import18.NgIf;
  _text_34:any;
  _anchor_35:any;
  /*private*/ _appEl_35:import2.AppElement;
  _TemplateRef_35_5:any;
  _NgFor_35_6:import19.NgFor;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  /*private*/ _appEl_38:import2.AppElement;
  _TabComponent_38_4:import17.TabComponent;
  _text_39:any;
  _anchor_40:any;
  /*private*/ _appEl_40:import2.AppElement;
  _TemplateRef_40_5:any;
  _NgIf_40_6:import18.NgIf;
  _text_41:any;
  _anchor_42:any;
  /*private*/ _appEl_42:import2.AppElement;
  _TemplateRef_42_5:any;
  _NgFor_42_6:import19.NgFor;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _anchor_46:any;
  /*private*/ _appEl_46:import2.AppElement;
  _TemplateRef_46_5:any;
  _NgIf_46_6:import18.NgIf;
  _text_47:any;
  _text_48:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HistoryComponent0,renderType_HistoryComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','app-root');
    this._text_1 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','album-art-background');
    this._el_3 = this.renderer.createElement(this._el_2,'img',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','content-top album-header');
    this._text_6 = this.renderer.createText(this._el_5,'\n		',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'div',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','row nav-bar');
    this._text_8 = this.renderer.createText(this._el_7,'\n			',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'zone-selector',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','col-xs-3');
    this._appEl_9 = new import2.AppElement(9,7,this,this._el_9);
    var compView_9:any = import20.viewFactory_ZoneSelectorComponent0(this.viewUtils,this.injector(9),this._appEl_9);
    this._ZoneSelectorComponent_9_4 = new import12.ZoneSelectorComponent(this.parentInjector.get(import21.AudioZoneService));
    this._appEl_9.initComponent(this._ZoneSelectorComponent_9_4,[],compView_9);
    compView_9.create(this._ZoneSelectorComponent_9_4,[],(null as any));
    this._text_10 = this.renderer.createText(this._el_7,'\n			',(null as any));
    this._el_11 = this.renderer.createElement(this._el_7,'search-bar',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','col-xs-9');
    this._appEl_11 = new import2.AppElement(11,7,this,this._el_11);
    var compView_11:any = import22.viewFactory_SearchBarComponent0(this.viewUtils,this.injector(11),this._appEl_11);
    this._SearchBarComponent_11_4 = new import13.SearchBarComponent(this.parentInjector.get(import23.Router));
    this._appEl_11.initComponent(this._SearchBarComponent_11_4,[],compView_11);
    compView_11.create(this._SearchBarComponent_11_4,[],(null as any));
    this._text_12 = this.renderer.createText(this._el_7,'\n		',(null as any));
    this._text_13 = this.renderer.createText(this._el_5,'\n		',(null as any));
    this._el_14 = this.renderer.createElement(this._el_5,'breadcrumbs',(null as any));
    this._appEl_14 = new import2.AppElement(14,5,this,this._el_14);
    var compView_14:any = import24.viewFactory_BreadcrumbsComponent0(this.viewUtils,this.injector(14),this._appEl_14);
    this._BreadcrumbsComponent_14_4 = new import14.BreadcrumbsComponent(this.parentInjector.get(import25.Location));
    this._appEl_14.initComponent(this._BreadcrumbsComponent_14_4,[],compView_14);
    compView_14.create(this._BreadcrumbsComponent_14_4,[],(null as any));
    this._text_15 = this.renderer.createText(this._el_5,'\n		',(null as any));
    this._el_16 = this.renderer.createElement(this._el_5,'h1',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','text-center');
    this._text_17 = this.renderer.createText(this._el_16,'History',(null as any));
    this._text_18 = this.renderer.createText(this._el_5,'\n	',(null as any));
    this._text_19 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_20 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','content-bottom');
    this._text_21 = this.renderer.createText(this._el_20,'\n		',(null as any));
    this._el_22 = this.renderer.createElement(this._el_20,'tabset',(null as any));
    this._appEl_22 = new import2.AppElement(22,20,this,this._el_22);
    var compView_22:any = import26.viewFactory_TabsetComponent0(this.viewUtils,this.injector(22),this._appEl_22);
    this._TabsetComponent_22_4 = new import15.TabsetComponent();
    this._query_TabComponent_22_0 = new import16.QueryList<any>();
    this._appEl_22.initComponent(this._TabsetComponent_22_4,[],compView_22);
    this._text_23 = this.renderer.createText((null as any),'\n			',(null as any));
    this._el_24 = this.renderer.createElement((null as any),'tab',(null as any));
    this.renderer.setElementAttribute(this._el_24,'heading','All');
    this._appEl_24 = new import2.AppElement(24,22,this,this._el_24);
    var compView_24:any = import27.viewFactory_TabComponent0(this.viewUtils,this.injector(24),this._appEl_24);
    this._TabComponent_24_4 = new import17.TabComponent();
    this._appEl_24.initComponent(this._TabComponent_24_4,[],compView_24);
    this._text_25 = this.renderer.createText((null as any),'\n				',(null as any));
    this._anchor_26 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_26 = new import2.AppElement(26,24,this,this._anchor_26);
    this._TemplateRef_26_5 = new import28.TemplateRef_(this._appEl_26,viewFactory_HistoryComponent1);
    this._NgIf_26_6 = new import18.NgIf(this._appEl_26.vcRef,this._TemplateRef_26_5);
    this._text_27 = this.renderer.createText((null as any),'\n				',(null as any));
    this._anchor_28 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_28 = new import2.AppElement(28,24,this,this._anchor_28);
    this._TemplateRef_28_5 = new import28.TemplateRef_(this._appEl_28,viewFactory_HistoryComponent2);
    this._NgFor_28_6 = new import19.NgFor(this._appEl_28.vcRef,this._TemplateRef_28_5,this.parentInjector.get(import29.IterableDiffers),this.ref);
    this._text_29 = this.renderer.createText((null as any),'\n			',(null as any));
      compView_24.create(this._TabComponent_24_4,[[].concat([
        this._text_25,
        this._appEl_26,
        this._text_27,
        this._appEl_28,
        this._text_29
      ]
    )],(null as any));
    this._text_30 = this.renderer.createText((null as any),'\n			',(null as any));
    this._el_31 = this.renderer.createElement((null as any),'tab',(null as any));
    this.renderer.setElementAttribute(this._el_31,'heading','Requested');
    this._appEl_31 = new import2.AppElement(31,22,this,this._el_31);
    var compView_31:any = import27.viewFactory_TabComponent0(this.viewUtils,this.injector(31),this._appEl_31);
    this._TabComponent_31_4 = new import17.TabComponent();
    this._appEl_31.initComponent(this._TabComponent_31_4,[],compView_31);
    this._text_32 = this.renderer.createText((null as any),'\n				',(null as any));
    this._anchor_33 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_33 = new import2.AppElement(33,31,this,this._anchor_33);
    this._TemplateRef_33_5 = new import28.TemplateRef_(this._appEl_33,viewFactory_HistoryComponent3);
    this._NgIf_33_6 = new import18.NgIf(this._appEl_33.vcRef,this._TemplateRef_33_5);
    this._text_34 = this.renderer.createText((null as any),'\n				',(null as any));
    this._anchor_35 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_35 = new import2.AppElement(35,31,this,this._anchor_35);
    this._TemplateRef_35_5 = new import28.TemplateRef_(this._appEl_35,viewFactory_HistoryComponent4);
    this._NgFor_35_6 = new import19.NgFor(this._appEl_35.vcRef,this._TemplateRef_35_5,this.parentInjector.get(import29.IterableDiffers),this.ref);
    this._text_36 = this.renderer.createText((null as any),'\n			',(null as any));
      compView_31.create(this._TabComponent_31_4,[[].concat([
        this._text_32,
        this._appEl_33,
        this._text_34,
        this._appEl_35,
        this._text_36
      ]
    )],(null as any));
    this._text_37 = this.renderer.createText((null as any),'\n			',(null as any));
    this._el_38 = this.renderer.createElement((null as any),'tab',(null as any));
    this.renderer.setElementAttribute(this._el_38,'heading','Mine');
    this._appEl_38 = new import2.AppElement(38,22,this,this._el_38);
    var compView_38:any = import27.viewFactory_TabComponent0(this.viewUtils,this.injector(38),this._appEl_38);
    this._TabComponent_38_4 = new import17.TabComponent();
    this._appEl_38.initComponent(this._TabComponent_38_4,[],compView_38);
    this._text_39 = this.renderer.createText((null as any),'\n				',(null as any));
    this._anchor_40 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_40 = new import2.AppElement(40,38,this,this._anchor_40);
    this._TemplateRef_40_5 = new import28.TemplateRef_(this._appEl_40,viewFactory_HistoryComponent5);
    this._NgIf_40_6 = new import18.NgIf(this._appEl_40.vcRef,this._TemplateRef_40_5);
    this._text_41 = this.renderer.createText((null as any),'\n				',(null as any));
    this._anchor_42 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_42 = new import2.AppElement(42,38,this,this._anchor_42);
    this._TemplateRef_42_5 = new import28.TemplateRef_(this._appEl_42,viewFactory_HistoryComponent6);
    this._NgFor_42_6 = new import19.NgFor(this._appEl_42.vcRef,this._TemplateRef_42_5,this.parentInjector.get(import29.IterableDiffers),this.ref);
    this._text_43 = this.renderer.createText((null as any),'\n			',(null as any));
      compView_38.create(this._TabComponent_38_4,[[].concat([
        this._text_39,
        this._appEl_40,
        this._text_41,
        this._appEl_42,
        this._text_43
      ]
    )],(null as any));
    this._text_44 = this.renderer.createText((null as any),'\n		',(null as any));
      compView_22.create(this._TabsetComponent_22_4,[[].concat([
        this._text_23,
        this._el_24,
        this._text_30,
        this._el_31,
        this._text_37,
        this._el_38,
        this._text_44
      ]
    )],(null as any));
    this._text_45 = this.renderer.createText(this._el_20,'\n		',(null as any));
    this._anchor_46 = this.renderer.createTemplateAnchor(this._el_20,(null as any));
    this._appEl_46 = new import2.AppElement(46,20,this,this._anchor_46);
    this._TemplateRef_46_5 = new import28.TemplateRef_(this._appEl_46,viewFactory_HistoryComponent7);
    this._NgIf_46_6 = new import18.NgIf(this._appEl_46.vcRef,this._TemplateRef_46_5);
    this._text_47 = this.renderer.createText(this._el_20,'\n	',(null as any));
    this._text_48 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_24,'select',this.eventHandler(this._handle_select_24_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    const subscription_0:any = this._TabComponent_24_4.select.subscribe(this.eventHandler(this._handle_select_24_0.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_31,'select',this.eventHandler(this._handle_select_31_0.bind(this)));
    this._expr_8 = import7.UNINITIALIZED;
    const subscription_1:any = this._TabComponent_31_4.select.subscribe(this.eventHandler(this._handle_select_31_0.bind(this)));
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_38,'select',this.eventHandler(this._handle_select_38_0.bind(this)));
    this._expr_12 = import7.UNINITIALIZED;
    const subscription_2:any = this._TabComponent_38_4.select.subscribe(this.eventHandler(this._handle_select_38_0.bind(this)));
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._anchor_26,
      this._text_27,
      this._anchor_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._anchor_33,
      this._text_34,
      this._anchor_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._anchor_40,
      this._text_41,
      this._anchor_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._anchor_46,
      this._text_47,
      this._text_48
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.ZoneSelectorComponent) && (9 === requestNodeIndex))) { return this._ZoneSelectorComponent_9_4; }
    if (((token === import13.SearchBarComponent) && (11 === requestNodeIndex))) { return this._SearchBarComponent_11_4; }
    if (((token === import14.BreadcrumbsComponent) && (14 === requestNodeIndex))) { return this._BreadcrumbsComponent_14_4; }
    if (((token === import28.TemplateRef) && (26 === requestNodeIndex))) { return this._TemplateRef_26_5; }
    if (((token === import18.NgIf) && (26 === requestNodeIndex))) { return this._NgIf_26_6; }
    if (((token === import28.TemplateRef) && (28 === requestNodeIndex))) { return this._TemplateRef_28_5; }
    if (((token === import19.NgFor) && (28 === requestNodeIndex))) { return this._NgFor_28_6; }
    if (((token === import17.TabComponent) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._TabComponent_24_4; }
    if (((token === import28.TemplateRef) && (33 === requestNodeIndex))) { return this._TemplateRef_33_5; }
    if (((token === import18.NgIf) && (33 === requestNodeIndex))) { return this._NgIf_33_6; }
    if (((token === import28.TemplateRef) && (35 === requestNodeIndex))) { return this._TemplateRef_35_5; }
    if (((token === import19.NgFor) && (35 === requestNodeIndex))) { return this._NgFor_35_6; }
    if (((token === import17.TabComponent) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._TabComponent_31_4; }
    if (((token === import28.TemplateRef) && (40 === requestNodeIndex))) { return this._TemplateRef_40_5; }
    if (((token === import18.NgIf) && (40 === requestNodeIndex))) { return this._NgIf_40_6; }
    if (((token === import28.TemplateRef) && (42 === requestNodeIndex))) { return this._TemplateRef_42_5; }
    if (((token === import19.NgFor) && (42 === requestNodeIndex))) { return this._NgFor_42_6; }
    if (((token === import17.TabComponent) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._TabComponent_38_4; }
    if (((token === import15.TabsetComponent) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._TabsetComponent_22_4; }
    if (((token === import28.TemplateRef) && (46 === requestNodeIndex))) { return this._TemplateRef_46_5; }
    if (((token === import18.NgIf) && (46 === requestNodeIndex))) { return this._NgIf_46_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_1:any = this.context.activeZone;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._ZoneSelectorComponent_9_4.activeZone = currVal_1;
      this._expr_1 = currVal_1;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ZoneSelectorComponent_9_4.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._SearchBarComponent_11_4.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._BreadcrumbsComponent_14_4.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TabsetComponent_22_4.ngOnInit(); }
    const currVal_4:any = 'All';
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._TabComponent_24_4.heading = currVal_4;
      this._expr_4 = currVal_4;
    }
    const currVal_5:boolean = (!this.context.loading && (this.context.history.length === 0));
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._NgIf_26_6.ngIf = currVal_5;
      this._expr_5 = currVal_5;
    }
    changes = (null as any);
    const currVal_6:any = this.context.history;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._NgFor_28_6.ngForOf = currVal_6;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_6,currVal_6);
      this._expr_6 = currVal_6;
    }
    if ((changes !== (null as any))) { this._NgFor_28_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_28_6.ngDoCheck(); }
    const currVal_8:any = 'Requested';
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._TabComponent_31_4.heading = currVal_8;
      this._expr_8 = currVal_8;
    }
    const currVal_9:boolean = (!this.context.loading && (this.context.requestHistory.length === 0));
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._NgIf_33_6.ngIf = currVal_9;
      this._expr_9 = currVal_9;
    }
    changes = (null as any);
    const currVal_10:any = this.context.requestHistory;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._NgFor_35_6.ngForOf = currVal_10;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_10,currVal_10);
      this._expr_10 = currVal_10;
    }
    if ((changes !== (null as any))) { this._NgFor_35_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_35_6.ngDoCheck(); }
    const currVal_12:any = 'Mine';
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._TabComponent_38_4.heading = currVal_12;
      this._expr_12 = currVal_12;
    }
    const currVal_13:boolean = (!this.context.loading && (this.context.userHistory.length === 0));
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._NgIf_40_6.ngIf = currVal_13;
      this._expr_13 = currVal_13;
    }
    changes = (null as any);
    const currVal_14:any = this.context.userHistory;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._NgFor_42_6.ngForOf = currVal_14;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_14,currVal_14);
      this._expr_14 = currVal_14;
    }
    if ((changes !== (null as any))) { this._NgFor_42_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_42_6.ngDoCheck(); }
    const currVal_15:any = this.context.loading;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this._NgIf_46_6.ngIf = currVal_15;
      this._expr_15 = currVal_15;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_TabComponent_22_0.dirty) {
        this._query_TabComponent_22_0.reset([
          this._TabComponent_24_4,
          this._TabComponent_31_4,
          this._TabComponent_38_4
        ]
        );
        this._TabsetComponent_22_4.tabs = this._query_TabComponent_22_0;
        this._query_TabComponent_22_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._TabsetComponent_22_4.ngAfterContentInit(); }
    }
    const currVal_0:any = (((this.context.album == (null as any))? (null as any): this.context.album.ArtworkUrlLarge) || '/assets/images/pixel.gif');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_3,'src',this.viewUtils.sanitizer.sanitize(import30.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    const currVal_2:any = this._TabsetComponent_22_4.clazz;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_22,'tab-container',currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_select_24_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.loadFullHistory()) !== false);
    return (true && pd_0);
  }
  private _handle_select_31_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.loadRequestHistory()) !== false);
    return (true && pd_0);
  }
  private _handle_select_38_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.loadUserHistory()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_HistoryComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.HistoryComponent> {
  if ((renderType_HistoryComponent === (null as any))) { (renderType_HistoryComponent = viewUtils.createRenderComponentType('C:/data/solutions/PlayMeExtension/src/app/history/history.component.html',0,import9.ViewEncapsulation.Emulated,styles_HistoryComponent,{})); }
  return new _View_HistoryComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_HistoryComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HistoryComponent1,renderType_HistoryComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'No results',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_HistoryComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HistoryComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_HistoryComponent2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _QueuedTrackComponent_0_4:import31.QueuedTrackComponent;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HistoryComponent2,renderType_HistoryComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'queued-track',(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import32.viewFactory_QueuedTrackComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._QueuedTrackComponent_0_4 = new import31.QueuedTrackComponent(this.parent.parentInjector.get(import8.QueueService));
    this._appEl_0.initComponent(this._QueuedTrackComponent_0_4,[],compView_0);
    compView_0.create(this._QueuedTrackComponent_0_4,[],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'likeTrack',this.eventHandler(this._handle_likeTrack_0_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_0,'vetoTrack',this.eventHandler(this._handle_vetoTrack_0_1.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    const subscription_0:any = this._QueuedTrackComponent_0_4.likeTrack.subscribe(this.eventHandler(this._handle_likeTrack_0_0.bind(this)));
    const subscription_1:any = this._QueuedTrackComponent_0_4.vetoTrack.subscribe(this.eventHandler(this._handle_vetoTrack_0_1.bind(this)));
    this.init([].concat([this._el_0]),[this._el_0],[
      disposable_0,
      disposable_1
    ]
    ,[
      subscription_0,
      subscription_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import31.QueuedTrackComponent) && (0 === requestNodeIndex))) { return this._QueuedTrackComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = this.context.$implicit;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._QueuedTrackComponent_0_4.queuedTrack = currVal_2;
      this._expr_2 = currVal_2;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._QueuedTrackComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_likeTrack_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.likeTrack(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_vetoTrack_0_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.vetoTrack(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_HistoryComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HistoryComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_HistoryComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HistoryComponent3,renderType_HistoryComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'No results',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_HistoryComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HistoryComponent3(viewUtils,parentInjector,declarationEl);
}
class _View_HistoryComponent4 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _QueuedTrackComponent_0_4:import31.QueuedTrackComponent;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HistoryComponent4,renderType_HistoryComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'queued-track',(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import32.viewFactory_QueuedTrackComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._QueuedTrackComponent_0_4 = new import31.QueuedTrackComponent(this.parent.parentInjector.get(import8.QueueService));
    this._appEl_0.initComponent(this._QueuedTrackComponent_0_4,[],compView_0);
    compView_0.create(this._QueuedTrackComponent_0_4,[],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'likeTrack',this.eventHandler(this._handle_likeTrack_0_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_0,'vetoTrack',this.eventHandler(this._handle_vetoTrack_0_1.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    const subscription_0:any = this._QueuedTrackComponent_0_4.likeTrack.subscribe(this.eventHandler(this._handle_likeTrack_0_0.bind(this)));
    const subscription_1:any = this._QueuedTrackComponent_0_4.vetoTrack.subscribe(this.eventHandler(this._handle_vetoTrack_0_1.bind(this)));
    this.init([].concat([this._el_0]),[this._el_0],[
      disposable_0,
      disposable_1
    ]
    ,[
      subscription_0,
      subscription_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import31.QueuedTrackComponent) && (0 === requestNodeIndex))) { return this._QueuedTrackComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = this.context.$implicit;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._QueuedTrackComponent_0_4.queuedTrack = currVal_2;
      this._expr_2 = currVal_2;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._QueuedTrackComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_likeTrack_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.likeTrack(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_vetoTrack_0_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.vetoTrack(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_HistoryComponent4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HistoryComponent4(viewUtils,parentInjector,declarationEl);
}
class _View_HistoryComponent5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HistoryComponent5,renderType_HistoryComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'No results',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_HistoryComponent5(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HistoryComponent5(viewUtils,parentInjector,declarationEl);
}
class _View_HistoryComponent6 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _QueuedTrackComponent_0_4:import31.QueuedTrackComponent;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HistoryComponent6,renderType_HistoryComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'queued-track',(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import32.viewFactory_QueuedTrackComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._QueuedTrackComponent_0_4 = new import31.QueuedTrackComponent(this.parent.parentInjector.get(import8.QueueService));
    this._appEl_0.initComponent(this._QueuedTrackComponent_0_4,[],compView_0);
    compView_0.create(this._QueuedTrackComponent_0_4,[],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'likeTrack',this.eventHandler(this._handle_likeTrack_0_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_0,'vetoTrack',this.eventHandler(this._handle_vetoTrack_0_1.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    const subscription_0:any = this._QueuedTrackComponent_0_4.likeTrack.subscribe(this.eventHandler(this._handle_likeTrack_0_0.bind(this)));
    const subscription_1:any = this._QueuedTrackComponent_0_4.vetoTrack.subscribe(this.eventHandler(this._handle_vetoTrack_0_1.bind(this)));
    this.init([].concat([this._el_0]),[this._el_0],[
      disposable_0,
      disposable_1
    ]
    ,[
      subscription_0,
      subscription_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import31.QueuedTrackComponent) && (0 === requestNodeIndex))) { return this._QueuedTrackComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = this.context.$implicit;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._QueuedTrackComponent_0_4.queuedTrack = currVal_2;
      this._expr_2 = currVal_2;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._QueuedTrackComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_likeTrack_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.likeTrack(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_vetoTrack_0_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.vetoTrack(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_HistoryComponent6(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HistoryComponent6(viewUtils,parentInjector,declarationEl);
}
class _View_HistoryComponent7 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HistoryComponent7,renderType_HistoryComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'loading...',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_HistoryComponent7(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HistoryComponent7(viewUtils,parentInjector,declarationEl);
}