/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['.breadcrumb[_ngcontent-%COMP%]{\r\n	margin-bottom: 0;\r\n}'];