/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../../app/shared/breadcrumbs/breadcrumbs.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/common/src/location/location';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from './breadcrumbs.component.css.shim';
import * as import12 from '@angular/router/src/directives/router_link';
import * as import13 from '@angular/router/src/router';
import * as import14 from '@angular/router/src/router_state';
import * as import15 from '@angular/common/src/location/location_strategy';
import * as import16 from '@angular/core/src/security';
var renderType_BreadcrumbsComponent_Host:import0.RenderComponentType = (null as any);
class _View_BreadcrumbsComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _BreadcrumbsComponent_0_4:import3.BreadcrumbsComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_BreadcrumbsComponent_Host0,renderType_BreadcrumbsComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('breadcrumbs',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_BreadcrumbsComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._BreadcrumbsComponent_0_4 = new import3.BreadcrumbsComponent(this.parentInjector.get(import8.Location));
    this._appEl_0.initComponent(this._BreadcrumbsComponent_0_4,[],compView_0);
    compView_0.create(this._BreadcrumbsComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.BreadcrumbsComponent) && (0 === requestNodeIndex))) { return this._BreadcrumbsComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._BreadcrumbsComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_BreadcrumbsComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_BreadcrumbsComponent_Host === (null as any))) { (renderType_BreadcrumbsComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_BreadcrumbsComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const BreadcrumbsComponentNgFactory:import10.ComponentFactory<import3.BreadcrumbsComponent> = new import10.ComponentFactory<import3.BreadcrumbsComponent>('breadcrumbs',viewFactory_BreadcrumbsComponent_Host0,import3.BreadcrumbsComponent);
const styles_BreadcrumbsComponent:any[] = [import11.styles];
var renderType_BreadcrumbsComponent:import0.RenderComponentType = (null as any);
class _View_BreadcrumbsComponent0 extends import1.AppView<import3.BreadcrumbsComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _el_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _el_8:any;
  _RouterLinkWithHref_8_3:import12.RouterLinkWithHref;
  _text_9:any;
  _text_10:any;
  _arr_0:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_BreadcrumbsComponent0,renderType_BreadcrumbsComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ol',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','breadcrumb');
    this._text_1 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'li',(null as any));
    this._el_3 = this.renderer.createElement(this._el_2,'a',(null as any));
    this.renderer.setElementAttribute(this._el_3,'href','#');
    this._el_4 = this.renderer.createElement(this._el_3,'i',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','icon-arrow-left');
    this._text_5 = this.renderer.createText(this._el_3,' back',(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_7 = this.renderer.createElement(this._el_0,'li',(null as any));
    this._el_8 = this.renderer.createElement(this._el_7,'a',(null as any));
    this._RouterLinkWithHref_8_3 = new import12.RouterLinkWithHref(this.parentInjector.get(import13.Router),this.parentInjector.get(import14.ActivatedRoute),this.parentInjector.get(import15.LocationStrategy));
    this._text_9 = this.renderer.createText(this._el_8,'Home',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_3,'click',this.eventHandler(this._handle_click_3_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_8,'click',this.eventHandler(this._handle_click_8_0.bind(this)));
    this._arr_0 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._el_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._el_8,
      this._text_9,
      this._text_10
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.RouterLinkWithHref) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._RouterLinkWithHref_8_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_2:any = this._arr_0('/');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._RouterLinkWithHref_8_3.routerLink = currVal_2;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_2,currVal_2);
      this._expr_2 = currVal_2;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_8_3.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_3:any = this._RouterLinkWithHref_8_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementProperty(this._el_8,'href',this.viewUtils.sanitizer.sanitize(import16.SecurityContext.URL,currVal_3));
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_8_3.ngOnDestroy();
  }
  private _handle_click_3_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.back()) !== false);
    return (true && pd_0);
  }
  private _handle_click_8_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_8_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_BreadcrumbsComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.BreadcrumbsComponent> {
  if ((renderType_BreadcrumbsComponent === (null as any))) { (renderType_BreadcrumbsComponent = viewUtils.createRenderComponentType('C:/data/solutions/PlayMeExtension/src/app/shared/breadcrumbs/breadcrumbs.component.html',0,import9.ViewEncapsulation.Emulated,styles_BreadcrumbsComponent,{})); }
  return new _View_BreadcrumbsComponent0(viewUtils,parentInjector,declarationEl);
}