/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../app/app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/forms/src/directives';
import * as import6 from '@angular/forms/src/form_providers';
import * as import7 from '@angular/router/src/router_module';
import * as import8 from '../../app/shared/shared.module';
import * as import9 from '@angular/http/src/http_module';
import * as import10 from '@angular/common/src/localization';
import * as import11 from '@angular/core/src/application_init';
import * as import12 from '@angular/core/src/testability/testability';
import * as import13 from '@angular/core/src/application_ref';
import * as import14 from '@angular/core/src/linker/compiler';
import * as import15 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import16 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import17 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import18 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import19 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import20 from '@angular/core/src/linker/view_utils';
import * as import21 from '@angular/platform-browser/src/browser/title';
import * as import22 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import23 from '@angular/http/src/backends/browser_xhr';
import * as import24 from '@angular/http/src/base_response_options';
import * as import25 from '@angular/http/src/backends/xhr_backend';
import * as import26 from '@angular/http/src/base_request_options';
import * as import27 from '@angular/common/src/location/location';
import * as import28 from '@angular/router/src/url_tree';
import * as import29 from '@angular/router/src/router_outlet_map';
import * as import30 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import31 from '../../app/api/audio-zone.service';
import * as import32 from '../../app/api/search.service';
import * as import33 from '../../app/api/artist.service';
import * as import34 from '../../app/api/album.service';
import * as import35 from '../../app/api/user-info.service';
import * as import36 from '../../app/api/queue.service';
import * as import37 from '../../app/api/signalr.service';
import * as import38 from '@angular/core/src/di/injector';
import * as import39 from './now-playing/now-playing.component.ngfactory';
import * as import40 from './album/album.component.ngfactory';
import * as import41 from './search/search.component.ngfactory';
import * as import42 from './artist/artist.component.ngfactory';
import * as import43 from './queue/queue.component.ngfactory';
import * as import44 from './history/history.component.ngfactory';
import * as import45 from './play-me-extension.component.ngfactory';
import * as import46 from '@angular/core/src/application_tokens';
import * as import47 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import48 from '@angular/platform-browser/src/dom/events/key_events';
import * as import49 from '@angular/core/src/zone/ng_zone';
import * as import50 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import51 from '@angular/common/src/location/platform_location';
import * as import52 from '@angular/common/src/location/location_strategy';
import * as import53 from '../../app/now-playing/now-playing.component';
import * as import54 from '../../app/album/album.component';
import * as import55 from '../../app/search/search.component';
import * as import56 from '../../app/artist/artist.component';
import * as import57 from '../../app/queue/queue.component';
import * as import58 from '../../app/history/history.component';
import * as import59 from '@angular/router/src/router';
import * as import60 from '@angular/core/src/console';
import * as import61 from '@angular/core/src/i18n/tokens';
import * as import62 from '@angular/core/src/error_handler';
import * as import63 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import64 from '@angular/platform-browser/src/dom/animation_driver';
import * as import65 from '@angular/core/src/render/api';
import * as import66 from '@angular/core/src/security';
import * as import67 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import68 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import69 from '@angular/http/src/interfaces';
import * as import70 from '@angular/http/src/http';
import * as import71 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import72 from '@angular/router/src/router_config_loader';
import * as import73 from '@angular/router/src/router_state';
import * as import74 from '@angular/core/src/i18n/tokens';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _InternalFormsSharedModule_3:import5.InternalFormsSharedModule;
  _FormsModule_4:import6.FormsModule;
  _ROUTER_FORROOT_GUARD_5:any;
  _RouterModule_6:import7.RouterModule;
  _SharedModule_7:import8.SharedModule;
  _HttpModule_8:import9.HttpModule;
  _AppModule_9:import1.AppModule;
  __LOCALE_ID_10:any;
  __NgLocalization_11:import10.NgLocaleLocalization;
  _ErrorHandler_12:any;
  _ApplicationInitStatus_13:import11.ApplicationInitStatus;
  _Testability_14:import12.Testability;
  _ApplicationRef__15:import13.ApplicationRef_;
  __ApplicationRef_16:any;
  __Compiler_17:import14.Compiler;
  __APP_ID_18:any;
  __DOCUMENT_19:any;
  __HAMMER_GESTURE_CONFIG_20:import15.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_21:any[];
  __EventManager_22:import16.EventManager;
  __DomSharedStylesHost_23:import17.DomSharedStylesHost;
  __AnimationDriver_24:any;
  __DomRootRenderer_25:import18.DomRootRenderer_;
  __RootRenderer_26:any;
  __DomSanitizer_27:import19.DomSanitizerImpl;
  __Sanitizer_28:any;
  __ViewUtils_29:import20.ViewUtils;
  __IterableDiffers_30:any;
  __KeyValueDiffers_31:any;
  __SharedStylesHost_32:any;
  __Title_33:import21.Title;
  __RadioControlRegistry_34:import22.RadioControlRegistry;
  __BrowserXhr_35:import23.BrowserXhr;
  __ResponseOptions_36:import24.BaseResponseOptions;
  __XSRFStrategy_37:any;
  __XHRBackend_38:import25.XHRBackend;
  __RequestOptions_39:import26.BaseRequestOptions;
  __Http_40:any;
  __ROUTER_CONFIGURATION_41:any;
  __LocationStrategy_42:any;
  __Location_43:import27.Location;
  __UrlSerializer_44:import28.DefaultUrlSerializer;
  __RouterOutletMap_45:import29.RouterOutletMap;
  __NgModuleFactoryLoader_46:import30.SystemJsNgModuleLoader;
  __ROUTES_47:any[];
  __Router_48:any;
  __ActivatedRoute_49:any;
  __APP_BOOTSTRAP_LISTENER_50:any[];
  __AudioZoneService_51:import31.AudioZoneService;
  __SearchService_52:import32.SearchService;
  __ArtistService_53:import33.ArtistService;
  __AlbumService_54:import34.AlbumService;
  __UserInfoService_55:import35.UserInfoService;
  __QueueService_56:import36.QueueService;
  __SignalRService_57:import37.SignalRService;
  __TRANSLATIONS_FORMAT_58:any;
  constructor(parent:import38.Injector) {
    super(parent,[
      import39.NowPlayingComponentNgFactory,
      import40.AlbumComponentNgFactory,
      import41.SearchComponentNgFactory,
      import42.ArtistComponentNgFactory,
      import43.QueueComponentNgFactory,
      import44.HistoryComponentNgFactory,
      import45.PlayMeExtensionAppComponentNgFactory
    ]
    ,[import45.PlayMeExtensionAppComponentNgFactory]);
  }
  get _LOCALE_ID_10():any {
    if ((this.__LOCALE_ID_10 == (null as any))) { (this.__LOCALE_ID_10 = (null as any)); }
    return this.__LOCALE_ID_10;
  }
  get _NgLocalization_11():import10.NgLocaleLocalization {
    if ((this.__NgLocalization_11 == (null as any))) { (this.__NgLocalization_11 = new import10.NgLocaleLocalization(this._LOCALE_ID_10)); }
    return this.__NgLocalization_11;
  }
  get _ApplicationRef_16():any {
    if ((this.__ApplicationRef_16 == (null as any))) { (this.__ApplicationRef_16 = this._ApplicationRef__15); }
    return this.__ApplicationRef_16;
  }
  get _Compiler_17():import14.Compiler {
    if ((this.__Compiler_17 == (null as any))) { (this.__Compiler_17 = new import14.Compiler()); }
    return this.__Compiler_17;
  }
  get _APP_ID_18():any {
    if ((this.__APP_ID_18 == (null as any))) { (this.__APP_ID_18 = import46._appIdRandomProviderFactory()); }
    return this.__APP_ID_18;
  }
  get _DOCUMENT_19():any {
    if ((this.__DOCUMENT_19 == (null as any))) { (this.__DOCUMENT_19 = import4._document()); }
    return this.__DOCUMENT_19;
  }
  get _HAMMER_GESTURE_CONFIG_20():import15.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_20 == (null as any))) { (this.__HAMMER_GESTURE_CONFIG_20 = new import15.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_20;
  }
  get _EVENT_MANAGER_PLUGINS_21():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_21 == (null as any))) { (this.__EVENT_MANAGER_PLUGINS_21 = [
      new import47.DomEventsPlugin(),
      new import48.KeyEventsPlugin(),
      new import15.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_20)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_21;
  }
  get _EventManager_22():import16.EventManager {
    if ((this.__EventManager_22 == (null as any))) { (this.__EventManager_22 = new import16.EventManager(this._EVENT_MANAGER_PLUGINS_21,this.parent.get(import49.NgZone))); }
    return this.__EventManager_22;
  }
  get _DomSharedStylesHost_23():import17.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_23 == (null as any))) { (this.__DomSharedStylesHost_23 = new import17.DomSharedStylesHost(this._DOCUMENT_19)); }
    return this.__DomSharedStylesHost_23;
  }
  get _AnimationDriver_24():any {
    if ((this.__AnimationDriver_24 == (null as any))) { (this.__AnimationDriver_24 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_24;
  }
  get _DomRootRenderer_25():import18.DomRootRenderer_ {
    if ((this.__DomRootRenderer_25 == (null as any))) { (this.__DomRootRenderer_25 = new import18.DomRootRenderer_(this._DOCUMENT_19,this._EventManager_22,this._DomSharedStylesHost_23,this._AnimationDriver_24)); }
    return this.__DomRootRenderer_25;
  }
  get _RootRenderer_26():any {
    if ((this.__RootRenderer_26 == (null as any))) { (this.__RootRenderer_26 = import50._createConditionalRootRenderer(this._DomRootRenderer_25,this.parent.get(import50.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_26;
  }
  get _DomSanitizer_27():import19.DomSanitizerImpl {
    if ((this.__DomSanitizer_27 == (null as any))) { (this.__DomSanitizer_27 = new import19.DomSanitizerImpl()); }
    return this.__DomSanitizer_27;
  }
  get _Sanitizer_28():any {
    if ((this.__Sanitizer_28 == (null as any))) { (this.__Sanitizer_28 = this._DomSanitizer_27); }
    return this.__Sanitizer_28;
  }
  get _ViewUtils_29():import20.ViewUtils {
    if ((this.__ViewUtils_29 == (null as any))) { (this.__ViewUtils_29 = new import20.ViewUtils(this._RootRenderer_26,this._APP_ID_18,this._Sanitizer_28)); }
    return this.__ViewUtils_29;
  }
  get _IterableDiffers_30():any {
    if ((this.__IterableDiffers_30 == (null as any))) { (this.__IterableDiffers_30 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_30;
  }
  get _KeyValueDiffers_31():any {
    if ((this.__KeyValueDiffers_31 == (null as any))) { (this.__KeyValueDiffers_31 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_31;
  }
  get _SharedStylesHost_32():any {
    if ((this.__SharedStylesHost_32 == (null as any))) { (this.__SharedStylesHost_32 = this._DomSharedStylesHost_23); }
    return this.__SharedStylesHost_32;
  }
  get _Title_33():import21.Title {
    if ((this.__Title_33 == (null as any))) { (this.__Title_33 = new import21.Title()); }
    return this.__Title_33;
  }
  get _RadioControlRegistry_34():import22.RadioControlRegistry {
    if ((this.__RadioControlRegistry_34 == (null as any))) { (this.__RadioControlRegistry_34 = new import22.RadioControlRegistry()); }
    return this.__RadioControlRegistry_34;
  }
  get _BrowserXhr_35():import23.BrowserXhr {
    if ((this.__BrowserXhr_35 == (null as any))) { (this.__BrowserXhr_35 = new import23.BrowserXhr()); }
    return this.__BrowserXhr_35;
  }
  get _ResponseOptions_36():import24.BaseResponseOptions {
    if ((this.__ResponseOptions_36 == (null as any))) { (this.__ResponseOptions_36 = new import24.BaseResponseOptions()); }
    return this.__ResponseOptions_36;
  }
  get _XSRFStrategy_37():any {
    if ((this.__XSRFStrategy_37 == (null as any))) { (this.__XSRFStrategy_37 = import9._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_37;
  }
  get _XHRBackend_38():import25.XHRBackend {
    if ((this.__XHRBackend_38 == (null as any))) { (this.__XHRBackend_38 = new import25.XHRBackend(this._BrowserXhr_35,this._ResponseOptions_36,this._XSRFStrategy_37)); }
    return this.__XHRBackend_38;
  }
  get _RequestOptions_39():import26.BaseRequestOptions {
    if ((this.__RequestOptions_39 == (null as any))) { (this.__RequestOptions_39 = new import26.BaseRequestOptions()); }
    return this.__RequestOptions_39;
  }
  get _Http_40():any {
    if ((this.__Http_40 == (null as any))) { (this.__Http_40 = import9.httpFactory(this._XHRBackend_38,this._RequestOptions_39)); }
    return this.__Http_40;
  }
  get _ROUTER_CONFIGURATION_41():any {
    if ((this.__ROUTER_CONFIGURATION_41 == (null as any))) { (this.__ROUTER_CONFIGURATION_41 = {useHash: true}); }
    return this.__ROUTER_CONFIGURATION_41;
  }
  get _LocationStrategy_42():any {
    if ((this.__LocationStrategy_42 == (null as any))) { (this.__LocationStrategy_42 = import7.provideLocationStrategy(this.parent.get(import51.PlatformLocation),this.parent.get(import52.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_41)); }
    return this.__LocationStrategy_42;
  }
  get _Location_43():import27.Location {
    if ((this.__Location_43 == (null as any))) { (this.__Location_43 = new import27.Location(this._LocationStrategy_42)); }
    return this.__Location_43;
  }
  get _UrlSerializer_44():import28.DefaultUrlSerializer {
    if ((this.__UrlSerializer_44 == (null as any))) { (this.__UrlSerializer_44 = new import28.DefaultUrlSerializer()); }
    return this.__UrlSerializer_44;
  }
  get _RouterOutletMap_45():import29.RouterOutletMap {
    if ((this.__RouterOutletMap_45 == (null as any))) { (this.__RouterOutletMap_45 = new import29.RouterOutletMap()); }
    return this.__RouterOutletMap_45;
  }
  get _NgModuleFactoryLoader_46():import30.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_46 == (null as any))) { (this.__NgModuleFactoryLoader_46 = new import30.SystemJsNgModuleLoader(this._Compiler_17,this.parent.get(import30.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_46;
  }
  get _ROUTES_47():any[] {
      if ((this.__ROUTES_47 == (null as any))) { (this.__ROUTES_47 = [[
        {
          path: '',
          redirectTo: '/now-playing',
          pathMatch: 'full'
        }
        ,
        {
          path: 'now-playing',
          component: import53.NowPlayingComponent
        }
        ,
        {
          path: 'album/:provider/:id',
          component: import54.AlbumComponent
        }
        ,
        {
          path: 'search/:provider/:searchQuery',
          component: import55.SearchComponent
        }
        ,
        {
          path: 'artist/:provider/:id',
          component: import56.ArtistComponent
        }
        ,
        {
          path: 'queue',
          component: import57.QueueComponent
        }
        ,
        {
          path: 'history',
          component: import58.HistoryComponent
        }

      ]
    ]); }
    return this.__ROUTES_47;
  }
  get _Router_48():any {
    if ((this.__Router_48 == (null as any))) { (this.__Router_48 = import7.setupRouter(this._ApplicationRef_16,this._UrlSerializer_44,this._RouterOutletMap_45,this._Location_43,this,this._NgModuleFactoryLoader_46,this._Compiler_17,this._ROUTES_47,this._ROUTER_CONFIGURATION_41)); }
    return this.__Router_48;
  }
  get _ActivatedRoute_49():any {
    if ((this.__ActivatedRoute_49 == (null as any))) { (this.__ActivatedRoute_49 = import7.rootRoute(this._Router_48)); }
    return this.__ActivatedRoute_49;
  }
  get _APP_BOOTSTRAP_LISTENER_50():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_50 == (null as any))) { (this.__APP_BOOTSTRAP_LISTENER_50 = [import7.initialRouterNavigation(this._Router_48,this._ROUTER_CONFIGURATION_41)]); }
    return this.__APP_BOOTSTRAP_LISTENER_50;
  }
  get _AudioZoneService_51():import31.AudioZoneService {
    if ((this.__AudioZoneService_51 == (null as any))) { (this.__AudioZoneService_51 = new import31.AudioZoneService()); }
    return this.__AudioZoneService_51;
  }
  get _SearchService_52():import32.SearchService {
    if ((this.__SearchService_52 == (null as any))) { (this.__SearchService_52 = new import32.SearchService(this._Http_40,this._AudioZoneService_51)); }
    return this.__SearchService_52;
  }
  get _ArtistService_53():import33.ArtistService {
    if ((this.__ArtistService_53 == (null as any))) { (this.__ArtistService_53 = new import33.ArtistService(this._Http_40,this._AudioZoneService_51)); }
    return this.__ArtistService_53;
  }
  get _AlbumService_54():import34.AlbumService {
    if ((this.__AlbumService_54 == (null as any))) { (this.__AlbumService_54 = new import34.AlbumService(this._Http_40,this._AudioZoneService_51)); }
    return this.__AlbumService_54;
  }
  get _UserInfoService_55():import35.UserInfoService {
    if ((this.__UserInfoService_55 == (null as any))) { (this.__UserInfoService_55 = new import35.UserInfoService(this._Http_40)); }
    return this.__UserInfoService_55;
  }
  get _QueueService_56():import36.QueueService {
    if ((this.__QueueService_56 == (null as any))) { (this.__QueueService_56 = new import36.QueueService(this._Http_40,this._AudioZoneService_51,this._UserInfoService_55)); }
    return this.__QueueService_56;
  }
  get _SignalRService_57():import37.SignalRService {
    if ((this.__SignalRService_57 == (null as any))) { (this.__SignalRService_57 = new import37.SignalRService(this._AudioZoneService_51,this._QueueService_56)); }
    return this.__SignalRService_57;
  }
  get _TRANSLATIONS_FORMAT_58():any {
    if ((this.__TRANSLATIONS_FORMAT_58 == (null as any))) { (this.__TRANSLATIONS_FORMAT_58 = (null as any)); }
    return this.__TRANSLATIONS_FORMAT_58;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._InternalFormsSharedModule_3 = new import5.InternalFormsSharedModule();
    this._FormsModule_4 = new import6.FormsModule();
    this._ROUTER_FORROOT_GUARD_5 = import7.provideForRootGuard(this.parent.get(import59.Router,(null as any)));
    this._RouterModule_6 = new import7.RouterModule(this._ROUTER_FORROOT_GUARD_5);
    this._SharedModule_7 = new import8.SharedModule();
    this._HttpModule_8 = new import9.HttpModule();
    this._AppModule_9 = new import1.AppModule();
    this._ErrorHandler_12 = import4.errorHandler();
    this._ApplicationInitStatus_13 = new import11.ApplicationInitStatus(this.parent.get(import11.APP_INITIALIZER,(null as any)));
    this._Testability_14 = new import12.Testability(this.parent.get(import49.NgZone));
    this._ApplicationRef__15 = new import13.ApplicationRef_(this.parent.get(import49.NgZone),this.parent.get(import60.Console),this,this._ErrorHandler_12,this,this._ApplicationInitStatus_13,this.parent.get(import12.TestabilityRegistry,(null as any)),this._Testability_14);
    return this._AppModule_9;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_3; }
    if ((token === import6.FormsModule)) { return this._FormsModule_4; }
    if ((token === import7.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_5; }
    if ((token === import7.RouterModule)) { return this._RouterModule_6; }
    if ((token === import8.SharedModule)) { return this._SharedModule_7; }
    if ((token === import9.HttpModule)) { return this._HttpModule_8; }
    if ((token === import1.AppModule)) { return this._AppModule_9; }
    if ((token === import61.LOCALE_ID)) { return this._LOCALE_ID_10; }
    if ((token === import10.NgLocalization)) { return this._NgLocalization_11; }
    if ((token === import62.ErrorHandler)) { return this._ErrorHandler_12; }
    if ((token === import11.ApplicationInitStatus)) { return this._ApplicationInitStatus_13; }
    if ((token === import12.Testability)) { return this._Testability_14; }
    if ((token === import13.ApplicationRef_)) { return this._ApplicationRef__15; }
    if ((token === import13.ApplicationRef)) { return this._ApplicationRef_16; }
    if ((token === import14.Compiler)) { return this._Compiler_17; }
    if ((token === import46.APP_ID)) { return this._APP_ID_18; }
    if ((token === import63.DOCUMENT)) { return this._DOCUMENT_19; }
    if ((token === import15.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_20; }
    if ((token === import16.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_21; }
    if ((token === import16.EventManager)) { return this._EventManager_22; }
    if ((token === import17.DomSharedStylesHost)) { return this._DomSharedStylesHost_23; }
    if ((token === import64.AnimationDriver)) { return this._AnimationDriver_24; }
    if ((token === import18.DomRootRenderer)) { return this._DomRootRenderer_25; }
    if ((token === import65.RootRenderer)) { return this._RootRenderer_26; }
    if ((token === import19.DomSanitizer)) { return this._DomSanitizer_27; }
    if ((token === import66.Sanitizer)) { return this._Sanitizer_28; }
    if ((token === import20.ViewUtils)) { return this._ViewUtils_29; }
    if ((token === import67.IterableDiffers)) { return this._IterableDiffers_30; }
    if ((token === import68.KeyValueDiffers)) { return this._KeyValueDiffers_31; }
    if ((token === import17.SharedStylesHost)) { return this._SharedStylesHost_32; }
    if ((token === import21.Title)) { return this._Title_33; }
    if ((token === import22.RadioControlRegistry)) { return this._RadioControlRegistry_34; }
    if ((token === import23.BrowserXhr)) { return this._BrowserXhr_35; }
    if ((token === import24.ResponseOptions)) { return this._ResponseOptions_36; }
    if ((token === import69.XSRFStrategy)) { return this._XSRFStrategy_37; }
    if ((token === import25.XHRBackend)) { return this._XHRBackend_38; }
    if ((token === import26.RequestOptions)) { return this._RequestOptions_39; }
    if ((token === import70.Http)) { return this._Http_40; }
    if ((token === import7.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_41; }
    if ((token === import52.LocationStrategy)) { return this._LocationStrategy_42; }
    if ((token === import27.Location)) { return this._Location_43; }
    if ((token === import28.UrlSerializer)) { return this._UrlSerializer_44; }
    if ((token === import29.RouterOutletMap)) { return this._RouterOutletMap_45; }
    if ((token === import71.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_46; }
    if ((token === import72.ROUTES)) { return this._ROUTES_47; }
    if ((token === import59.Router)) { return this._Router_48; }
    if ((token === import73.ActivatedRoute)) { return this._ActivatedRoute_49; }
    if ((token === import46.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_50; }
    if ((token === import31.AudioZoneService)) { return this._AudioZoneService_51; }
    if ((token === import32.SearchService)) { return this._SearchService_52; }
    if ((token === import33.ArtistService)) { return this._ArtistService_53; }
    if ((token === import34.AlbumService)) { return this._AlbumService_54; }
    if ((token === import35.UserInfoService)) { return this._UserInfoService_55; }
    if ((token === import36.QueueService)) { return this._QueueService_56; }
    if ((token === import37.SignalRService)) { return this._SignalRService_57; }
    if ((token === import74.TRANSLATIONS_FORMAT)) { return this._TRANSLATIONS_FORMAT_58; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__15.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);