/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['.btn-icon[_ngcontent-%COMP%] {\r\n	line-height: 16px;\r\n}'];