/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../app/queue/queue.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../../app/api/queue.service';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from './queue.component.css.shim';
import * as import12 from '../../../app/now-playing/zone-selector/zone-selector.component';
import * as import13 from '../../../app/shared/search-bar/search-bar.component';
import * as import14 from '../../../app/shared/breadcrumbs/breadcrumbs.component';
import * as import15 from '@angular/common/src/directives/ng_for';
import * as import16 from '../now-playing/zone-selector/zone-selector.component.ngfactory';
import * as import17 from '../../../app/api/audio-zone.service';
import * as import18 from '../shared/search-bar/search-bar.component.ngfactory';
import * as import19 from '@angular/router/src/router';
import * as import20 from '../shared/breadcrumbs/breadcrumbs.component.ngfactory';
import * as import21 from '@angular/common/src/location/location';
import * as import22 from '@angular/core/src/linker/template_ref';
import * as import23 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import24 from '@angular/core/src/security';
import * as import25 from '../../../app/shared/queued-track/queued-track.component';
import * as import26 from '../shared/queued-track/queued-track.component.ngfactory';
var renderType_QueueComponent_Host:import0.RenderComponentType = (null as any);
class _View_QueueComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _QueueComponent_0_4:import3.QueueComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_QueueComponent_Host0,renderType_QueueComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-queue',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_QueueComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._QueueComponent_0_4 = new import3.QueueComponent(this.parentInjector.get(import8.QueueService));
    this._appEl_0.initComponent(this._QueueComponent_0_4,[],compView_0);
    compView_0.create(this._QueueComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.QueueComponent) && (0 === requestNodeIndex))) { return this._QueueComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._QueueComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_QueueComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_QueueComponent_Host === (null as any))) { (renderType_QueueComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_QueueComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const QueueComponentNgFactory:import10.ComponentFactory<import3.QueueComponent> = new import10.ComponentFactory<import3.QueueComponent>('app-queue',viewFactory_QueueComponent_Host0,import3.QueueComponent);
const styles_QueueComponent:any[] = [import11.styles];
var renderType_QueueComponent:import0.RenderComponentType = (null as any);
class _View_QueueComponent0 extends import1.AppView<import3.QueueComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _ZoneSelectorComponent_9_4:import12.ZoneSelectorComponent;
  _text_10:any;
  _el_11:any;
  /*private*/ _appEl_11:import2.AppElement;
  _SearchBarComponent_11_4:import13.SearchBarComponent;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import2.AppElement;
  _BreadcrumbsComponent_14_4:import14.BreadcrumbsComponent;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _anchor_22:any;
  /*private*/ _appEl_22:import2.AppElement;
  _TemplateRef_22_5:any;
  _NgFor_22_6:import15.NgFor;
  _text_23:any;
  _text_24:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_QueueComponent0,renderType_QueueComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','app-root');
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','album-art-background');
    this._el_3 = this.renderer.createElement(this._el_2,'img',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','content-top album-header');
    this._text_6 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'div',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','row nav-bar');
    this._text_8 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'zone-selector',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','col-xs-3');
    this._appEl_9 = new import2.AppElement(9,7,this,this._el_9);
    var compView_9:any = import16.viewFactory_ZoneSelectorComponent0(this.viewUtils,this.injector(9),this._appEl_9);
    this._ZoneSelectorComponent_9_4 = new import12.ZoneSelectorComponent(this.parentInjector.get(import17.AudioZoneService));
    this._appEl_9.initComponent(this._ZoneSelectorComponent_9_4,[],compView_9);
    compView_9.create(this._ZoneSelectorComponent_9_4,[],(null as any));
    this._text_10 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_7,'search-bar',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','col-xs-9');
    this._appEl_11 = new import2.AppElement(11,7,this,this._el_11);
    var compView_11:any = import18.viewFactory_SearchBarComponent0(this.viewUtils,this.injector(11),this._appEl_11);
    this._SearchBarComponent_11_4 = new import13.SearchBarComponent(this.parentInjector.get(import19.Router));
    this._appEl_11.initComponent(this._SearchBarComponent_11_4,[],compView_11);
    compView_11.create(this._SearchBarComponent_11_4,[],(null as any));
    this._text_12 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._text_13 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_5,'breadcrumbs',(null as any));
    this._appEl_14 = new import2.AppElement(14,5,this,this._el_14);
    var compView_14:any = import20.viewFactory_BreadcrumbsComponent0(this.viewUtils,this.injector(14),this._appEl_14);
    this._BreadcrumbsComponent_14_4 = new import14.BreadcrumbsComponent(this.parentInjector.get(import21.Location));
    this._appEl_14.initComponent(this._BreadcrumbsComponent_14_4,[],compView_14);
    compView_14.create(this._BreadcrumbsComponent_14_4,[],(null as any));
    this._text_15 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_5,'h1',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','text-center');
    this._text_17 = this.renderer.createText(this._el_16,'Queue',(null as any));
    this._text_18 = this.renderer.createText(this._el_5,'\n  ',(null as any));
    this._text_19 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','content-bottom');
    this._text_21 = this.renderer.createText(this._el_20,'\n    ',(null as any));
    this._anchor_22 = this.renderer.createTemplateAnchor(this._el_20,(null as any));
    this._appEl_22 = new import2.AppElement(22,20,this,this._anchor_22);
    this._TemplateRef_22_5 = new import22.TemplateRef_(this._appEl_22,viewFactory_QueueComponent1);
    this._NgFor_22_6 = new import15.NgFor(this._appEl_22.vcRef,this._TemplateRef_22_5,this.parentInjector.get(import23.IterableDiffers),this.ref);
    this._text_23 = this.renderer.createText(this._el_20,'\n  ',(null as any));
    this._text_24 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._anchor_22,
      this._text_23,
      this._text_24
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.ZoneSelectorComponent) && (9 === requestNodeIndex))) { return this._ZoneSelectorComponent_9_4; }
    if (((token === import13.SearchBarComponent) && (11 === requestNodeIndex))) { return this._SearchBarComponent_11_4; }
    if (((token === import14.BreadcrumbsComponent) && (14 === requestNodeIndex))) { return this._BreadcrumbsComponent_14_4; }
    if (((token === import22.TemplateRef) && (22 === requestNodeIndex))) { return this._TemplateRef_22_5; }
    if (((token === import15.NgFor) && (22 === requestNodeIndex))) { return this._NgFor_22_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_1:any = this.context.activeZone;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._ZoneSelectorComponent_9_4.activeZone = currVal_1;
      this._expr_1 = currVal_1;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ZoneSelectorComponent_9_4.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._SearchBarComponent_11_4.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._BreadcrumbsComponent_14_4.ngOnInit(); }
    changes = (null as any);
    const currVal_2:any = this.context.queuedTracks;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgFor_22_6.ngForOf = currVal_2;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_2,currVal_2);
      this._expr_2 = currVal_2;
    }
    if ((changes !== (null as any))) { this._NgFor_22_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_22_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = (((this.context.album == (null as any))? (null as any): this.context.album.ArtworkUrlLarge) || '/assets/images/pixel.gif');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_3,'src',this.viewUtils.sanitizer.sanitize(import24.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_QueueComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.QueueComponent> {
  if ((renderType_QueueComponent === (null as any))) { (renderType_QueueComponent = viewUtils.createRenderComponentType('C:/data/solutions/PlayMeExtension/src/app/queue/queue.component.html',0,import9.ViewEncapsulation.Emulated,styles_QueueComponent,{})); }
  return new _View_QueueComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_QueueComponent1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _QueuedTrackComponent_0_4:import25.QueuedTrackComponent;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_QueueComponent1,renderType_QueueComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'queued-track',(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import26.viewFactory_QueuedTrackComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._QueuedTrackComponent_0_4 = new import25.QueuedTrackComponent(this.parent.parentInjector.get(import8.QueueService));
    this._appEl_0.initComponent(this._QueuedTrackComponent_0_4,[],compView_0);
    compView_0.create(this._QueuedTrackComponent_0_4,[],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'likeTrack',this.eventHandler(this._handle_likeTrack_0_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_0,'vetoTrack',this.eventHandler(this._handle_vetoTrack_0_1.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    const subscription_0:any = this._QueuedTrackComponent_0_4.likeTrack.subscribe(this.eventHandler(this._handle_likeTrack_0_0.bind(this)));
    const subscription_1:any = this._QueuedTrackComponent_0_4.vetoTrack.subscribe(this.eventHandler(this._handle_vetoTrack_0_1.bind(this)));
    this.init([].concat([this._el_0]),[this._el_0],[
      disposable_0,
      disposable_1
    ]
    ,[
      subscription_0,
      subscription_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import25.QueuedTrackComponent) && (0 === requestNodeIndex))) { return this._QueuedTrackComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = this.context.$implicit;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._QueuedTrackComponent_0_4.queuedTrack = currVal_2;
      this._expr_2 = currVal_2;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._QueuedTrackComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_likeTrack_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.likeTrack(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_vetoTrack_0_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.vetoTrack(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_QueueComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_QueueComponent1(viewUtils,parentInjector,declarationEl);
}