/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../../app/shared/simple-track-list-item/simple-track-list-item.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../../../app/api/queue.service';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from './simple-track-list-item.component.css.shim';
import * as import12 from '../../../../app/shared/queue-track-button/queue-track-button.component';
import * as import13 from '../queue-track-button/queue-track-button.component.ngfactory';
var renderType_SimpleTrackListItemComponent_Host:import0.RenderComponentType = (null as any);
class _View_SimpleTrackListItemComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _SimpleTrackListItemComponent_0_4:import3.SimpleTrackListItemComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SimpleTrackListItemComponent_Host0,renderType_SimpleTrackListItemComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('simple-track-list-item',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SimpleTrackListItemComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SimpleTrackListItemComponent_0_4 = new import3.SimpleTrackListItemComponent(this.parentInjector.get(import8.QueueService));
    this._appEl_0.initComponent(this._SimpleTrackListItemComponent_0_4,[],compView_0);
    compView_0.create(this._SimpleTrackListItemComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.SimpleTrackListItemComponent) && (0 === requestNodeIndex))) { return this._SimpleTrackListItemComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_SimpleTrackListItemComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_SimpleTrackListItemComponent_Host === (null as any))) { (renderType_SimpleTrackListItemComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_SimpleTrackListItemComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const SimpleTrackListItemComponentNgFactory:import10.ComponentFactory<import3.SimpleTrackListItemComponent> = new import10.ComponentFactory<import3.SimpleTrackListItemComponent>('simple-track-list-item',viewFactory_SimpleTrackListItemComponent_Host0,import3.SimpleTrackListItemComponent);
const styles_SimpleTrackListItemComponent:any[] = [import11.styles];
var renderType_SimpleTrackListItemComponent:import0.RenderComponentType = (null as any);
class _View_SimpleTrackListItemComponent0 extends import1.AppView<import3.SimpleTrackListItemComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  /*private*/ _appEl_8:import2.AppElement;
  _QueueTrackButtonComponent_8_4:import12.QueueTrackButtonComponent;
  _text_9:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SimpleTrackListItemComponent0,renderType_SimpleTrackListItemComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','row');
    this._text_1 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','col-xs-8');
    this._text_3 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'label',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','track-name');
    this._text_5 = this.renderer.createText(this._el_4,'',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n	',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_8 = this.renderer.createElement(this._el_0,'queue-track-button',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','col-xs-4 text-right');
    this._appEl_8 = new import2.AppElement(8,0,this,this._el_8);
    var compView_8:any = import13.viewFactory_QueueTrackButtonComponent0(this.viewUtils,this.injector(8),this._appEl_8);
    this._QueueTrackButtonComponent_8_4 = new import12.QueueTrackButtonComponent(this.parentInjector.get(import8.QueueService));
    this._appEl_8.initComponent(this._QueueTrackButtonComponent_8_4,[],compView_8);
    compView_8.create(this._QueueTrackButtonComponent_8_4,[],(null as any));
    this._text_9 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.QueueTrackButtonComponent) && (8 === requestNodeIndex))) { return this._QueueTrackButtonComponent_8_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = this.context.track;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._QueueTrackButtonComponent_8_4.track = currVal_1;
      this._expr_1 = currVal_1;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._QueueTrackButtonComponent_8_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.context.track.Name,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_5,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_SimpleTrackListItemComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.SimpleTrackListItemComponent> {
  if ((renderType_SimpleTrackListItemComponent === (null as any))) { (renderType_SimpleTrackListItemComponent = viewUtils.createRenderComponentType('C:/data/solutions/PlayMeExtension/src/app/shared/simple-track-list-item/simple-track-list-item.component.html',0,import9.ViewEncapsulation.Emulated,styles_SimpleTrackListItemComponent,{})); }
  return new _View_SimpleTrackListItemComponent0(viewUtils,parentInjector,declarationEl);
}