/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../../app/shared/track-list-item/track-list-item.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../../../app/api/queue.service';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '@angular/common/src/directives/ng_for';
import * as import12 from '@angular/router/src/directives/router_link';
import * as import13 from '../../../../app/shared/queue-track-button/queue-track-button.component';
import * as import14 from '@angular/core/src/linker/template_ref';
import * as import15 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import16 from '@angular/router/src/router';
import * as import17 from '@angular/router/src/router_state';
import * as import18 from '@angular/common/src/location/location_strategy';
import * as import19 from '../queue-track-button/queue-track-button.component.ngfactory';
import * as import20 from '@angular/core/src/security';
var renderType_TrackListItemComponent_Host:import0.RenderComponentType = (null as any);
class _View_TrackListItemComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _TrackListItemComponent_0_4:import3.TrackListItemComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_TrackListItemComponent_Host0,renderType_TrackListItemComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('track-list-item',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_TrackListItemComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._TrackListItemComponent_0_4 = new import3.TrackListItemComponent(this.parentInjector.get(import8.QueueService));
    this._appEl_0.initComponent(this._TrackListItemComponent_0_4,[],compView_0);
    compView_0.create(this._TrackListItemComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.TrackListItemComponent) && (0 === requestNodeIndex))) { return this._TrackListItemComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_TrackListItemComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_TrackListItemComponent_Host === (null as any))) { (renderType_TrackListItemComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_TrackListItemComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const TrackListItemComponentNgFactory:import10.ComponentFactory<import3.TrackListItemComponent> = new import10.ComponentFactory<import3.TrackListItemComponent>('track-list-item',viewFactory_TrackListItemComponent_Host0,import3.TrackListItemComponent);
const styles_TrackListItemComponent:any[] = [];
var renderType_TrackListItemComponent:import0.RenderComponentType = (null as any);
class _View_TrackListItemComponent0 extends import1.AppView<import3.TrackListItemComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _anchor_14:any;
  /*private*/ _appEl_14:import2.AppElement;
  _TemplateRef_14_5:any;
  _NgFor_14_6:import11.NgFor;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _RouterLinkWithHref_17_3:import12.RouterLinkWithHref;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  /*private*/ _appEl_21:import2.AppElement;
  _QueueTrackButtonComponent_21_4:import13.QueueTrackButtonComponent;
  _text_22:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  _arr_0:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_TrackListItemComponent0,renderType_TrackListItemComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','row track-list-item');
    this._text_1 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','col-xs-2');
    this._text_3 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'img',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','img-responsive');
    this._text_5 = this.renderer.createText(this._el_2,'\n	',(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_7 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','col-xs-7');
    this._text_8 = this.renderer.createText(this._el_7,'\n		',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'label',(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'',(null as any));
    this._text_11 = this.renderer.createText(this._el_7,'\n		',(null as any));
    this._el_12 = this.renderer.createElement(this._el_7,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','comma-separated');
    this._text_13 = this.renderer.createText(this._el_12,'\n			',(null as any));
    this._anchor_14 = this.renderer.createTemplateAnchor(this._el_12,(null as any));
    this._appEl_14 = new import2.AppElement(14,12,this,this._anchor_14);
    this._TemplateRef_14_5 = new import14.TemplateRef_(this._appEl_14,viewFactory_TrackListItemComponent1);
    this._NgFor_14_6 = new import11.NgFor(this._appEl_14.vcRef,this._TemplateRef_14_5,this.parentInjector.get(import15.IterableDiffers),this.ref);
    this._text_15 = this.renderer.createText(this._el_12,'\n		',(null as any));
    this._text_16 = this.renderer.createText(this._el_7,'\n		',(null as any));
    this._el_17 = this.renderer.createElement(this._el_7,'a',(null as any));
    this._RouterLinkWithHref_17_3 = new import12.RouterLinkWithHref(this.parentInjector.get(import16.Router),this.parentInjector.get(import17.ActivatedRoute),this.parentInjector.get(import18.LocationStrategy));
    this._text_18 = this.renderer.createText(this._el_17,'',(null as any));
    this._text_19 = this.renderer.createText(this._el_7,'\n	',(null as any));
    this._text_20 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_21 = this.renderer.createElement(this._el_0,'queue-track-button',(null as any));
    this.renderer.setElementAttribute(this._el_21,'class','col-xs-3 text-right');
    this._appEl_21 = new import2.AppElement(21,0,this,this._el_21);
    var compView_21:any = import19.viewFactory_QueueTrackButtonComponent0(this.viewUtils,this.injector(21),this._appEl_21);
    this._QueueTrackButtonComponent_21_4 = new import13.QueueTrackButtonComponent(this.parentInjector.get(import8.QueueService));
    this._appEl_21.initComponent(this._QueueTrackButtonComponent_21_4,[],compView_21);
    compView_21.create(this._QueueTrackButtonComponent_21_4,[],(null as any));
    this._text_22 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_17,'click',this.eventHandler(this._handle_click_17_0.bind(this)));
    this._arr_0 = import4.pureProxy3((p0:any,p1:any,p2:any):any[] => {
      return [
        p0,
        p1,
        p2
      ]
      ;
    });
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._anchor_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.TemplateRef) && (14 === requestNodeIndex))) { return this._TemplateRef_14_5; }
    if (((token === import11.NgFor) && (14 === requestNodeIndex))) { return this._NgFor_14_6; }
    if (((token === import12.RouterLinkWithHref) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._RouterLinkWithHref_17_3; }
    if (((token === import13.QueueTrackButtonComponent) && (21 === requestNodeIndex))) { return this._QueueTrackButtonComponent_21_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_2:any = ((this.context.track == (null as any))? (null as any): this.context.track.Artists);
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgFor_14_6.ngForOf = currVal_2;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_2,currVal_2);
      this._expr_2 = currVal_2;
    }
    if ((changes !== (null as any))) { this._NgFor_14_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_14_6.ngDoCheck(); }
    changes = (null as any);
    const currVal_4:any = this._arr_0('/album',((this.context.track == (null as any))? (null as any): this.context.track.Album.MusicProvider.Identifier),((this.context.track == (null as any))? (null as any): this.context.track.Album.Link));
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._RouterLinkWithHref_17_3.routerLink = currVal_4;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_4,currVal_4);
      this._expr_4 = currVal_4;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_17_3.ngOnChanges(changes); }
    const currVal_7:any = this.context.track;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._QueueTrackButtonComponent_21_4.track = currVal_7;
      this._expr_7 = currVal_7;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._QueueTrackButtonComponent_21_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = ((this.context.track == (null as any))? (null as any): this.context.track.Album.ArtworkUrlSmall);
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_4,'src',this.viewUtils.sanitizer.sanitize(import20.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'',((this.context.track == (null as any))? (null as any): this.context.track.Name),'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_10,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_5:any = this._RouterLinkWithHref_17_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementProperty(this._el_17,'href',this.viewUtils.sanitizer.sanitize(import20.SecurityContext.URL,currVal_5));
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = import4.interpolate(1,'',((this.context.track == (null as any))? (null as any): ((this.context.track.Album == (null as any))? (null as any): this.context.track.Album.Name)),'');
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setText(this._text_18,currVal_6);
      this._expr_6 = currVal_6;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_17_3.ngOnDestroy();
  }
  private _handle_click_17_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_17_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_TrackListItemComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.TrackListItemComponent> {
  if ((renderType_TrackListItemComponent === (null as any))) { (renderType_TrackListItemComponent = viewUtils.createRenderComponentType('C:/data/solutions/PlayMeExtension/src/app/shared/track-list-item/track-list-item.component.html',0,import9.ViewEncapsulation.None,styles_TrackListItemComponent,{})); }
  return new _View_TrackListItemComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_TrackListItemComponent1 extends import1.AppView<any> {
  _el_0:any;
  _el_1:any;
  _RouterLinkWithHref_1_3:import12.RouterLinkWithHref;
  _text_2:any;
  _arr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_TrackListItemComponent1,renderType_TrackListItemComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'li',(null as any));
    this._el_1 = this.renderer.createElement(this._el_0,'a',(null as any));
    this._RouterLinkWithHref_1_3 = new import12.RouterLinkWithHref(this.parent.parentInjector.get(import16.Router),this.parent.parentInjector.get(import17.ActivatedRoute),this.parent.parentInjector.get(import18.LocationStrategy));
    this._text_2 = this.renderer.createText(this._el_1,'',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_1,'click',this.eventHandler(this._handle_click_1_0.bind(this)));
    this._arr_0 = import4.pureProxy3((p0:any,p1:any,p2:any):any[] => {
      return [
        p0,
        p1,
        p2
      ]
      ;
    });
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.RouterLinkWithHref) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 2)))) { return this._RouterLinkWithHref_1_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_1:any = this._arr_0('/artist',this.context.$implicit.MusicProvider.Identifier,this.context.$implicit.Link);
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._RouterLinkWithHref_1_3.routerLink = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_1_3.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = this._RouterLinkWithHref_1_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_1,'href',this.viewUtils.sanitizer.sanitize(import20.SecurityContext.URL,currVal_2));
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import4.interpolate(1,'',this.context.$implicit.Name,'');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_2,currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_1_3.ngOnDestroy();
  }
  private _handle_click_1_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_1_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_TrackListItemComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_TrackListItemComponent1(viewUtils,parentInjector,declarationEl);
}