/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../../app/search/artist-list-item/artist-list-item.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from './artist-list-item.component.css.shim';
import * as import11 from '@angular/router/src/directives/router_link';
import * as import12 from '@angular/common/src/directives/ng_style';
import * as import13 from '@angular/router/src/router';
import * as import14 from '@angular/router/src/router_state';
import * as import15 from '@angular/common/src/location/location_strategy';
import * as import16 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import17 from '@angular/core/src/linker/element_ref';
import * as import18 from '@angular/core/src/security';
var renderType_ArtistListItemComponent_Host:import0.RenderComponentType = (null as any);
class _View_ArtistListItemComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ArtistListItemComponent_0_4:import3.ArtistListItemComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ArtistListItemComponent_Host0,renderType_ArtistListItemComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('artist-list-item',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ArtistListItemComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ArtistListItemComponent_0_4 = new import3.ArtistListItemComponent();
    this._appEl_0.initComponent(this._ArtistListItemComponent_0_4,[],compView_0);
    compView_0.create(this._ArtistListItemComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ArtistListItemComponent) && (0 === requestNodeIndex))) { return this._ArtistListItemComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_ArtistListItemComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ArtistListItemComponent_Host === (null as any))) { (renderType_ArtistListItemComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_ArtistListItemComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ArtistListItemComponentNgFactory:import9.ComponentFactory<import3.ArtistListItemComponent> = new import9.ComponentFactory<import3.ArtistListItemComponent>('artist-list-item',viewFactory_ArtistListItemComponent_Host0,import3.ArtistListItemComponent);
const styles_ArtistListItemComponent:any[] = [import10.styles];
var renderType_ArtistListItemComponent:import0.RenderComponentType = (null as any);
class _View_ArtistListItemComponent0 extends import1.AppView<import3.ArtistListItemComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _RouterLinkWithHref_2_3:import11.RouterLinkWithHref;
  _text_3:any;
  _el_4:any;
  _NgStyle_4_3:import12.NgStyle;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _RouterLinkWithHref_9_3:import11.RouterLinkWithHref;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  /*private*/ _expr_1:any;
  _arr_0:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  _map_0:any;
  /*private*/ _expr_5:any;
  _arr_1:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ArtistListItemComponent0,renderType_ArtistListItemComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','artist-tile col-xs-4');
    this._text_1 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'a',(null as any));
    this._RouterLinkWithHref_2_3 = new import11.RouterLinkWithHref(this.parentInjector.get(import13.Router),this.parentInjector.get(import14.ActivatedRoute),this.parentInjector.get(import15.LocationStrategy));
    this._text_3 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'img',(null as any));
    this.renderer.setElementAttribute(this._el_4,'src','/assets/images/pixel.gif');
    this._NgStyle_4_3 = new import12.NgStyle(this.parentInjector.get(import16.KeyValueDiffers),new import17.ElementRef(this._el_4),this.renderer);
    this._text_5 = this.renderer.createText(this._el_2,'\n	',(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n		\n	',(null as any));
    this._el_7 = this.renderer.createElement(this._el_0,'div',(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n		',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'a',(null as any));
    this._RouterLinkWithHref_9_3 = new import11.RouterLinkWithHref(this.parentInjector.get(import13.Router),this.parentInjector.get(import14.ActivatedRoute),this.parentInjector.get(import15.LocationStrategy));
    this._text_10 = this.renderer.createText(this._el_9,'',(null as any));
    this._text_11 = this.renderer.createText(this._el_7,'\n	',(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._arr_0 = import4.pureProxy3((p0:any,p1:any,p2:any):any[] => {
      return [
        p0,
        p1,
        p2
      ]
      ;
    });
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._map_0 = import4.pureProxy1((p0:any):{[key: string]:any} => {
      return {'background-image': p0};
    });
    this._expr_5 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_9,'click',this.eventHandler(this._handle_click_9_0.bind(this)));
    this._arr_1 = import4.pureProxy3((p0:any,p1:any,p2:any):any[] => {
      return [
        p0,
        p1,
        p2
      ]
      ;
    });
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.NgStyle) && (4 === requestNodeIndex))) { return this._NgStyle_4_3; }
    if (((token === import11.RouterLinkWithHref) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._RouterLinkWithHref_2_3; }
    if (((token === import11.RouterLinkWithHref) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._RouterLinkWithHref_9_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_2:any = this._arr_0('/artist',this.context.artist.MusicProvider.Identifier,this.context.artist.Link);
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._RouterLinkWithHref_2_3.routerLink = currVal_2;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_2,currVal_2);
      this._expr_2 = currVal_2;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_2_3.ngOnChanges(changes); }
    const currVal_5:any = this._map_0((('url(' + this.context.artist.PortraitUrlLarge) + ')'));
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._NgStyle_4_3.ngStyle = currVal_5;
      this._expr_5 = currVal_5;
    }
    if (!throwOnChange) { this._NgStyle_4_3.ngDoCheck(); }
    changes = (null as any);
    const currVal_7:any = this._arr_1('/artist',this.context.artist.MusicProvider.Identifier,this.context.artist.Link);
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._RouterLinkWithHref_9_3.routerLink = currVal_7;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_7,currVal_7);
      this._expr_7 = currVal_7;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_9_3.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = this.context.artist.Name;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementAttribute(this._el_2,'title',((currVal_1 == (null as any))? (null as any): currVal_1.toString()));
      this._expr_1 = currVal_1;
    }
    const currVal_3:any = this._RouterLinkWithHref_2_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementProperty(this._el_2,'href',this.viewUtils.sanitizer.sanitize(import18.SecurityContext.URL,currVal_3));
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this.context.artist.Name;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementAttribute(this._el_4,'alt',((currVal_4 == (null as any))? (null as any): currVal_4.toString()));
      this._expr_4 = currVal_4;
    }
    const currVal_8:any = this._RouterLinkWithHref_9_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementProperty(this._el_9,'href',this.viewUtils.sanitizer.sanitize(import18.SecurityContext.URL,currVal_8));
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = import4.interpolate(1,'',this.context.artist.Name,'');
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setText(this._text_10,currVal_9);
      this._expr_9 = currVal_9;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_2_3.ngOnDestroy();
    this._RouterLinkWithHref_9_3.ngOnDestroy();
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_2_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_9_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_9_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_ArtistListItemComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ArtistListItemComponent> {
  if ((renderType_ArtistListItemComponent === (null as any))) { (renderType_ArtistListItemComponent = viewUtils.createRenderComponentType('C:/data/solutions/PlayMeExtension/src/app/search/artist-list-item/artist-list-item.component.html',0,import8.ViewEncapsulation.Emulated,styles_ArtistListItemComponent,{})); }
  return new _View_ArtistListItemComponent0(viewUtils,parentInjector,declarationEl);
}