/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../app/artist/artist.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/router/src/router_state';
import * as import9 from '../../../app/api/artist.service';
import * as import10 from '@angular/common/src/location/location';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from './artist.component.css.shim';
import * as import14 from '@angular/common/src/directives/ng_style';
import * as import15 from '../../../app/now-playing/zone-selector/zone-selector.component';
import * as import16 from '../../../app/shared/search-bar/search-bar.component';
import * as import17 from '../../../app/shared/breadcrumbs/breadcrumbs.component';
import * as import18 from '@angular/common/src/directives/ng_for';
import * as import19 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import20 from '@angular/core/src/linker/element_ref';
import * as import21 from '../now-playing/zone-selector/zone-selector.component.ngfactory';
import * as import22 from '../../../app/api/audio-zone.service';
import * as import23 from '../shared/search-bar/search-bar.component.ngfactory';
import * as import24 from '@angular/router/src/router';
import * as import25 from '../shared/breadcrumbs/breadcrumbs.component.ngfactory';
import * as import26 from '@angular/core/src/linker/template_ref';
import * as import27 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import28 from '../../../app/search/album-list-item/album-list-item.component';
import * as import29 from '../search/album-list-item/album-list-item.component.ngfactory';
var renderType_ArtistComponent_Host:import0.RenderComponentType = (null as any);
class _View_ArtistComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ArtistComponent_0_4:import3.ArtistComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ArtistComponent_Host0,renderType_ArtistComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('artist',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ArtistComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ArtistComponent_0_4 = new import3.ArtistComponent(this.parentInjector.get(import8.ActivatedRoute),this.parentInjector.get(import9.ArtistService),this.parentInjector.get(import10.Location));
    this._appEl_0.initComponent(this._ArtistComponent_0_4,[],compView_0);
    compView_0.create(this._ArtistComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ArtistComponent) && (0 === requestNodeIndex))) { return this._ArtistComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ArtistComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ArtistComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ArtistComponent_Host === (null as any))) { (renderType_ArtistComponent_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,[],{})); }
  return new _View_ArtistComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ArtistComponentNgFactory:import12.ComponentFactory<import3.ArtistComponent> = new import12.ComponentFactory<import3.ArtistComponent>('artist',viewFactory_ArtistComponent_Host0,import3.ArtistComponent);
const styles_ArtistComponent:any[] = [import13.styles];
var renderType_ArtistComponent:import0.RenderComponentType = (null as any);
class _View_ArtistComponent0 extends import1.AppView<import3.ArtistComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _NgStyle_2_3:import14.NgStyle;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  /*private*/ _appEl_8:import2.AppElement;
  _ZoneSelectorComponent_8_4:import15.ZoneSelectorComponent;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import2.AppElement;
  _SearchBarComponent_10_4:import16.SearchBarComponent;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  /*private*/ _appEl_13:import2.AppElement;
  _BreadcrumbsComponent_13_4:import17.BreadcrumbsComponent;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _anchor_23:any;
  /*private*/ _appEl_23:import2.AppElement;
  _TemplateRef_23_5:any;
  _NgFor_23_6:import18.NgFor;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _map_0:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ArtistComponent0,renderType_ArtistComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','app-root');
    this._text_1 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','artist-art-background');
    this._NgStyle_2_3 = new import14.NgStyle(this.parentInjector.get(import19.KeyValueDiffers),new import20.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_4 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','content-top artist-header');
    this._text_5 = this.renderer.createText(this._el_4,'\n		',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','row nav-bar');
    this._text_7 = this.renderer.createText(this._el_6,'\n			',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'zone-selector',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','col-xs-3');
    this._appEl_8 = new import2.AppElement(8,6,this,this._el_8);
    var compView_8:any = import21.viewFactory_ZoneSelectorComponent0(this.viewUtils,this.injector(8),this._appEl_8);
    this._ZoneSelectorComponent_8_4 = new import15.ZoneSelectorComponent(this.parentInjector.get(import22.AudioZoneService));
    this._appEl_8.initComponent(this._ZoneSelectorComponent_8_4,[],compView_8);
    compView_8.create(this._ZoneSelectorComponent_8_4,[],(null as any));
    this._text_9 = this.renderer.createText(this._el_6,'\n			',(null as any));
    this._el_10 = this.renderer.createElement(this._el_6,'search-bar',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','col-xs-9');
    this._appEl_10 = new import2.AppElement(10,6,this,this._el_10);
    var compView_10:any = import23.viewFactory_SearchBarComponent0(this.viewUtils,this.injector(10),this._appEl_10);
    this._SearchBarComponent_10_4 = new import16.SearchBarComponent(this.parentInjector.get(import24.Router));
    this._appEl_10.initComponent(this._SearchBarComponent_10_4,[],compView_10);
    compView_10.create(this._SearchBarComponent_10_4,[],(null as any));
    this._text_11 = this.renderer.createText(this._el_6,'\n		',(null as any));
    this._text_12 = this.renderer.createText(this._el_4,'\n		',(null as any));
    this._el_13 = this.renderer.createElement(this._el_4,'breadcrumbs',(null as any));
    this._appEl_13 = new import2.AppElement(13,4,this,this._el_13);
    var compView_13:any = import25.viewFactory_BreadcrumbsComponent0(this.viewUtils,this.injector(13),this._appEl_13);
    this._BreadcrumbsComponent_13_4 = new import17.BreadcrumbsComponent(this.parentInjector.get(import10.Location));
    this._appEl_13.initComponent(this._BreadcrumbsComponent_13_4,[],compView_13);
    compView_13.create(this._BreadcrumbsComponent_13_4,[],(null as any));
    this._text_14 = this.renderer.createText(this._el_4,'\n		',(null as any));
    this._el_15 = this.renderer.createElement(this._el_4,'h1',(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'',(null as any));
    this._text_17 = this.renderer.createText(this._el_4,'\n	',(null as any));
    this._text_18 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_19 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','content-bottom');
    this._text_20 = this.renderer.createText(this._el_19,'\n		',(null as any));
    this._el_21 = this.renderer.createElement(this._el_19,'div',(null as any));
    this.renderer.setElementAttribute(this._el_21,'class','row');
    this._text_22 = this.renderer.createText(this._el_21,'\n			',(null as any));
    this._anchor_23 = this.renderer.createTemplateAnchor(this._el_21,(null as any));
    this._appEl_23 = new import2.AppElement(23,21,this,this._anchor_23);
    this._TemplateRef_23_5 = new import26.TemplateRef_(this._appEl_23,viewFactory_ArtistComponent1);
    this._NgFor_23_6 = new import18.NgFor(this._appEl_23.vcRef,this._TemplateRef_23_5,this.parentInjector.get(import27.IterableDiffers),this.ref);
    this._text_24 = this.renderer.createText(this._el_21,'\n		',(null as any));
    this._text_25 = this.renderer.createText(this._el_19,'\n	',(null as any));
    this._text_26 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._map_0 = import4.pureProxy1((p0:any):{[key: string]:any} => {
      return {'background-image': p0};
    });
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._anchor_23,
      this._text_24,
      this._text_25,
      this._text_26
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.NgStyle) && (2 === requestNodeIndex))) { return this._NgStyle_2_3; }
    if (((token === import15.ZoneSelectorComponent) && (8 === requestNodeIndex))) { return this._ZoneSelectorComponent_8_4; }
    if (((token === import16.SearchBarComponent) && (10 === requestNodeIndex))) { return this._SearchBarComponent_10_4; }
    if (((token === import17.BreadcrumbsComponent) && (13 === requestNodeIndex))) { return this._BreadcrumbsComponent_13_4; }
    if (((token === import26.TemplateRef) && (23 === requestNodeIndex))) { return this._TemplateRef_23_5; }
    if (((token === import18.NgFor) && (23 === requestNodeIndex))) { return this._NgFor_23_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_0:any = this._map_0((('url(' + ((this.context.artist == (null as any))? (null as any): this.context.artist.PortraitUrlLarge)) + ')'));
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgStyle_2_3.ngStyle = currVal_0;
      this._expr_0 = currVal_0;
    }
    if (!throwOnChange) { this._NgStyle_2_3.ngDoCheck(); }
    const currVal_1:any = this.context.activeZone;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._ZoneSelectorComponent_8_4.activeZone = currVal_1;
      this._expr_1 = currVal_1;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ZoneSelectorComponent_8_4.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._SearchBarComponent_10_4.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._BreadcrumbsComponent_13_4.ngOnInit(); }
    changes = (null as any);
    const currVal_3:any = ((this.context.artist == (null as any))? (null as any): this.context.artist.Albums);
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgFor_23_6.ngForOf = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._NgFor_23_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_23_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = import4.interpolate(1,'',((this.context.artist == (null as any))? (null as any): this.context.artist.Name),'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_16,currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_ArtistComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ArtistComponent> {
  if ((renderType_ArtistComponent === (null as any))) { (renderType_ArtistComponent = viewUtils.createRenderComponentType('C:/data/solutions/PlayMeExtension/src/app/artist/artist.component.html',0,import11.ViewEncapsulation.Emulated,styles_ArtistComponent,{})); }
  return new _View_ArtistComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_ArtistComponent1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _AlbumListItemComponent_0_4:import28.AlbumListItemComponent;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ArtistComponent1,renderType_ArtistComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'album-list-item',(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import29.viewFactory_AlbumListItemComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._AlbumListItemComponent_0_4 = new import28.AlbumListItemComponent();
    this._appEl_0.initComponent(this._AlbumListItemComponent_0_4,[],compView_0);
    compView_0.create(this._AlbumListItemComponent_0_4,[],(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import28.AlbumListItemComponent) && (0 === requestNodeIndex))) { return this._AlbumListItemComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.$implicit;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._AlbumListItemComponent_0_4.album = currVal_0;
      this._expr_0 = currVal_0;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ArtistComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ArtistComponent1(viewUtils,parentInjector,declarationEl);
}