/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../../app/shared/queued-track/queued-track.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../../../app/api/queue.service';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from './queued-track.component.css';
import * as import12 from '@angular/common/src/directives/ng_if';
import * as import13 from '@angular/common/src/pipes/date_pipe';
import * as import14 from '@angular/core/src/linker/template_ref';
import * as import15 from '@angular/core/src/i18n/tokens';
import * as import16 from '@angular/core/src/security';
import * as import17 from '@angular/common/src/directives/ng_for';
import * as import18 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import19 from '@angular/router/src/directives/router_link';
import * as import20 from '@angular/router/src/router';
import * as import21 from '@angular/router/src/router_state';
import * as import22 from '@angular/common/src/location/location_strategy';
import * as import23 from '@angular/common/src/directives/ng_class';
import * as import24 from '../../../../app/shared/opinion-buttons/opinion-buttons.component';
import * as import25 from '../opinion-buttons/opinion-buttons.component.ngfactory';
import * as import26 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import27 from '@angular/core/src/linker/element_ref';
import * as import28 from '../../../../app/shared/queue-track-button/queue-track-button.component';
import * as import29 from '../queue-track-button/queue-track-button.component.ngfactory';
import * as import30 from '@angular/common/src/pipes/async_pipe';
import * as import31 from '../../../../app/shared/user-list/user-list.component';
import * as import32 from '../user-list/user-list.component.ngfactory';
var renderType_QueuedTrackComponent_Host:import0.RenderComponentType = (null as any);
class _View_QueuedTrackComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _QueuedTrackComponent_0_4:import3.QueuedTrackComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_QueuedTrackComponent_Host0,renderType_QueuedTrackComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('queued-track',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_QueuedTrackComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._QueuedTrackComponent_0_4 = new import3.QueuedTrackComponent(this.parentInjector.get(import8.QueueService));
    this._appEl_0.initComponent(this._QueuedTrackComponent_0_4,[],compView_0);
    compView_0.create(this._QueuedTrackComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.QueuedTrackComponent) && (0 === requestNodeIndex))) { return this._QueuedTrackComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._QueuedTrackComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_QueuedTrackComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_QueuedTrackComponent_Host === (null as any))) { (renderType_QueuedTrackComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_QueuedTrackComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const QueuedTrackComponentNgFactory:import10.ComponentFactory<import3.QueuedTrackComponent> = new import10.ComponentFactory<import3.QueuedTrackComponent>('queued-track',viewFactory_QueuedTrackComponent_Host0,import3.QueuedTrackComponent);
const styles_QueuedTrackComponent:any[] = [import11.styles];
var renderType_QueuedTrackComponent:import0.RenderComponentType = (null as any);
class _View_QueuedTrackComponent0 extends import1.AppView<import3.QueuedTrackComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _anchor_16:any;
  /*private*/ _appEl_16:import2.AppElement;
  _TemplateRef_16_5:any;
  _NgIf_16_6:import12.NgIf;
  _text_17:any;
  _anchor_18:any;
  /*private*/ _appEl_18:import2.AppElement;
  _TemplateRef_18_5:any;
  _NgIf_18_6:import12.NgIf;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _anchor_22:any;
  /*private*/ _appEl_22:import2.AppElement;
  _TemplateRef_22_5:any;
  _NgIf_22_6:import12.NgIf;
  _text_23:any;
  _anchor_24:any;
  /*private*/ _appEl_24:import2.AppElement;
  _TemplateRef_24_5:any;
  _NgIf_24_6:import12.NgIf;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _anchor_29:any;
  /*private*/ _appEl_29:import2.AppElement;
  _TemplateRef_29_5:any;
  _NgIf_29_6:import12.NgIf;
  _text_30:any;
  _anchor_31:any;
  /*private*/ _appEl_31:import2.AppElement;
  _TemplateRef_31_5:any;
  _NgIf_31_6:import12.NgIf;
  _text_32:any;
  _anchor_33:any;
  /*private*/ _appEl_33:import2.AppElement;
  _TemplateRef_33_5:any;
  _NgIf_33_6:import12.NgIf;
  _text_34:any;
  _anchor_35:any;
  /*private*/ _appEl_35:import2.AppElement;
  _TemplateRef_35_5:any;
  _NgIf_35_6:import12.NgIf;
  _text_36:any;
  _anchor_37:any;
  /*private*/ _appEl_37:import2.AppElement;
  _TemplateRef_37_5:any;
  _NgIf_37_6:import12.NgIf;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  _pipe_date_0:import13.DatePipe;
  /*private*/ _expr_10:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_QueuedTrackComponent0,renderType_QueuedTrackComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','row track-list-item');
    this._text_1 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','col-xs-2');
    this._text_3 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'img',(null as any));
    this._text_5 = this.renderer.createText(this._el_2,'\n	',(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_7 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','col-xs-10');
    this._text_8 = this.renderer.createText(this._el_7,'\n		',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'div',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','row');
    this._text_10 = this.renderer.createText(this._el_9,'\n			',(null as any));
    this._el_11 = this.renderer.createElement(this._el_9,'div',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','col-xs-8');
    this._text_12 = this.renderer.createText(this._el_11,'\n				',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'label',(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'',(null as any));
    this._text_15 = this.renderer.createText(this._el_11,'\n				',(null as any));
    this._anchor_16 = this.renderer.createTemplateAnchor(this._el_11,(null as any));
    this._appEl_16 = new import2.AppElement(16,11,this,this._anchor_16);
    this._TemplateRef_16_5 = new import14.TemplateRef_(this._appEl_16,viewFactory_QueuedTrackComponent1);
    this._NgIf_16_6 = new import12.NgIf(this._appEl_16.vcRef,this._TemplateRef_16_5);
    this._text_17 = this.renderer.createText(this._el_11,'\n				',(null as any));
    this._anchor_18 = this.renderer.createTemplateAnchor(this._el_11,(null as any));
    this._appEl_18 = new import2.AppElement(18,11,this,this._anchor_18);
    this._TemplateRef_18_5 = new import14.TemplateRef_(this._appEl_18,viewFactory_QueuedTrackComponent3);
    this._NgIf_18_6 = new import12.NgIf(this._appEl_18.vcRef,this._TemplateRef_18_5);
    this._el_19 = this.renderer.createElement(this._el_11,'br',(null as any));
    this._text_20 = this.renderer.createText(this._el_11,'\n			',(null as any));
    this._text_21 = this.renderer.createText(this._el_9,'\n\n			',(null as any));
    this._anchor_22 = this.renderer.createTemplateAnchor(this._el_9,(null as any));
    this._appEl_22 = new import2.AppElement(22,9,this,this._anchor_22);
    this._TemplateRef_22_5 = new import14.TemplateRef_(this._appEl_22,viewFactory_QueuedTrackComponent4);
    this._NgIf_22_6 = new import12.NgIf(this._appEl_22.vcRef,this._TemplateRef_22_5);
    this._text_23 = this.renderer.createText(this._el_9,'\n\n			',(null as any));
    this._anchor_24 = this.renderer.createTemplateAnchor(this._el_9,(null as any));
    this._appEl_24 = new import2.AppElement(24,9,this,this._anchor_24);
    this._TemplateRef_24_5 = new import14.TemplateRef_(this._appEl_24,viewFactory_QueuedTrackComponent5);
    this._NgIf_24_6 = new import12.NgIf(this._appEl_24.vcRef,this._TemplateRef_24_5);
    this._text_25 = this.renderer.createText(this._el_9,'\n		',(null as any));
    this._text_26 = this.renderer.createText(this._el_7,'\n		',(null as any));
    this._el_27 = this.renderer.createElement(this._el_7,'div',(null as any));
    this.renderer.setElementAttribute(this._el_27,'class','queue-info');
    this._text_28 = this.renderer.createText(this._el_27,'\n			Queued by ',(null as any));
    this._anchor_29 = this.renderer.createTemplateAnchor(this._el_27,(null as any));
    this._appEl_29 = new import2.AppElement(29,27,this,this._anchor_29);
    this._TemplateRef_29_5 = new import14.TemplateRef_(this._appEl_29,viewFactory_QueuedTrackComponent6);
    this._NgIf_29_6 = new import12.NgIf(this._appEl_29.vcRef,this._TemplateRef_29_5);
    this._text_30 = this.renderer.createText(this._el_27,' ',(null as any));
    this._anchor_31 = this.renderer.createTemplateAnchor(this._el_27,(null as any));
    this._appEl_31 = new import2.AppElement(31,27,this,this._anchor_31);
    this._TemplateRef_31_5 = new import14.TemplateRef_(this._appEl_31,viewFactory_QueuedTrackComponent7);
    this._NgIf_31_6 = new import12.NgIf(this._appEl_31.vcRef,this._TemplateRef_31_5);
    this._text_32 = this.renderer.createText(this._el_27,'\n			',(null as any));
    this._anchor_33 = this.renderer.createTemplateAnchor(this._el_27,(null as any));
    this._appEl_33 = new import2.AppElement(33,27,this,this._anchor_33);
    this._TemplateRef_33_5 = new import14.TemplateRef_(this._appEl_33,viewFactory_QueuedTrackComponent8);
    this._NgIf_33_6 = new import12.NgIf(this._appEl_33.vcRef,this._TemplateRef_33_5);
    this._text_34 = this.renderer.createText(this._el_27,'\n			',(null as any));
    this._anchor_35 = this.renderer.createTemplateAnchor(this._el_27,(null as any));
    this._appEl_35 = new import2.AppElement(35,27,this,this._anchor_35);
    this._TemplateRef_35_5 = new import14.TemplateRef_(this._appEl_35,viewFactory_QueuedTrackComponent9);
    this._NgIf_35_6 = new import12.NgIf(this._appEl_35.vcRef,this._TemplateRef_35_5);
    this._text_36 = this.renderer.createText(this._el_27,'\n\n			',(null as any));
    this._anchor_37 = this.renderer.createTemplateAnchor(this._el_27,(null as any));
    this._appEl_37 = new import2.AppElement(37,27,this,this._anchor_37);
    this._TemplateRef_37_5 = new import14.TemplateRef_(this._appEl_37,viewFactory_QueuedTrackComponent10);
    this._NgIf_37_6 = new import12.NgIf(this._appEl_37.vcRef,this._TemplateRef_37_5);
    this._text_38 = this.renderer.createText(this._el_27,'\n		',(null as any));
    this._text_39 = this.renderer.createText(this._el_7,'\n	',(null as any));
    this._text_40 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._pipe_date_0 = new import13.DatePipe(this.parentInjector.get(import15.LOCALE_ID));
    this._expr_10 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._anchor_16,
      this._text_17,
      this._anchor_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._anchor_22,
      this._text_23,
      this._anchor_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._anchor_29,
      this._text_30,
      this._anchor_31,
      this._text_32,
      this._anchor_33,
      this._text_34,
      this._anchor_35,
      this._text_36,
      this._anchor_37,
      this._text_38,
      this._text_39,
      this._text_40
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.TemplateRef) && (16 === requestNodeIndex))) { return this._TemplateRef_16_5; }
    if (((token === import12.NgIf) && (16 === requestNodeIndex))) { return this._NgIf_16_6; }
    if (((token === import14.TemplateRef) && (18 === requestNodeIndex))) { return this._TemplateRef_18_5; }
    if (((token === import12.NgIf) && (18 === requestNodeIndex))) { return this._NgIf_18_6; }
    if (((token === import14.TemplateRef) && (22 === requestNodeIndex))) { return this._TemplateRef_22_5; }
    if (((token === import12.NgIf) && (22 === requestNodeIndex))) { return this._NgIf_22_6; }
    if (((token === import14.TemplateRef) && (24 === requestNodeIndex))) { return this._TemplateRef_24_5; }
    if (((token === import12.NgIf) && (24 === requestNodeIndex))) { return this._NgIf_24_6; }
    if (((token === import14.TemplateRef) && (29 === requestNodeIndex))) { return this._TemplateRef_29_5; }
    if (((token === import12.NgIf) && (29 === requestNodeIndex))) { return this._NgIf_29_6; }
    if (((token === import14.TemplateRef) && (31 === requestNodeIndex))) { return this._TemplateRef_31_5; }
    if (((token === import12.NgIf) && (31 === requestNodeIndex))) { return this._NgIf_31_6; }
    if (((token === import14.TemplateRef) && (33 === requestNodeIndex))) { return this._TemplateRef_33_5; }
    if (((token === import12.NgIf) && (33 === requestNodeIndex))) { return this._NgIf_33_6; }
    if (((token === import14.TemplateRef) && (35 === requestNodeIndex))) { return this._TemplateRef_35_5; }
    if (((token === import12.NgIf) && (35 === requestNodeIndex))) { return this._NgIf_35_6; }
    if (((token === import14.TemplateRef) && (37 === requestNodeIndex))) { return this._TemplateRef_37_5; }
    if (((token === import12.NgIf) && (37 === requestNodeIndex))) { return this._NgIf_37_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = ((this.context.queuedTrack == (null as any))? (null as any): ((this.context.queuedTrack.Track == (null as any))? (null as any): this.context.queuedTrack.Track.Artists));
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgIf_16_6.ngIf = currVal_2;
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = ((this.context.queuedTrack == (null as any))? (null as any): ((this.context.queuedTrack.Track == (null as any))? (null as any): this.context.queuedTrack.Track.Album));
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgIf_18_6.ngIf = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_4:boolean = !this.context.queuedTrack.StartedPlayingDateTime;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgIf_22_6.ngIf = currVal_4;
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this.context.queuedTrack.StartedPlayingDateTime;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._NgIf_24_6.ngIf = currVal_5;
      this._expr_5 = currVal_5;
    }
    const currVal_6:boolean = !this.context.queuedTrack.url;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._NgIf_29_6.ngIf = currVal_6;
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this.context.queuedTrack.url;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._NgIf_31_6.ngIf = currVal_7;
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this.context.queuedTrack.Reason;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._NgIf_33_6.ngIf = currVal_8;
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this.context.queuedTrack.StartedPlayingDateTime;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._NgIf_35_6.ngIf = currVal_9;
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this.context.queuedTrack.StartedPlayingDateTime;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._NgIf_37_6.ngIf = currVal_10;
      this._expr_10 = currVal_10;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = (((this.context.queuedTrack.Track == (null as any))? (null as any): ((this.context.queuedTrack.Track.Album == (null as any))? (null as any): this.context.queuedTrack.Track.Album.ArtworkUrlSmall)) || '/assets/images/pixel.gif');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_4,'src',this.viewUtils.sanitizer.sanitize(import16.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'',this.context.queuedTrack.Track.Name,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_14,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_QueuedTrackComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.QueuedTrackComponent> {
  if ((renderType_QueuedTrackComponent === (null as any))) { (renderType_QueuedTrackComponent = viewUtils.createRenderComponentType('C:/data/solutions/PlayMeExtension/src/app/shared/queued-track/queued-track.component.html',0,import9.ViewEncapsulation.None,styles_QueuedTrackComponent,{})); }
  return new _View_QueuedTrackComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_QueuedTrackComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgFor_2_6:import17.NgFor;
  _text_3:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_QueuedTrackComponent1,renderType_QueuedTrackComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ul',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','comma-separated');
    this._text_1 = this.renderer.createText(this._el_0,'\n					',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import14.TemplateRef_(this._appEl_2,viewFactory_QueuedTrackComponent2);
    this._NgFor_2_6 = new import17.NgFor(this._appEl_2.vcRef,this._TemplateRef_2_5,this.parent.parentInjector.get(import18.IterableDiffers),this.parent.ref);
    this._text_3 = this.renderer.createText(this._el_0,'\n				',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import17.NgFor) && (2 === requestNodeIndex))) { return this._NgFor_2_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = ((this.parent.context.queuedTrack.Track == (null as any))? (null as any): this.parent.context.queuedTrack.Track.Artists);
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgFor_2_6.ngForOf = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._NgFor_2_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_2_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_QueuedTrackComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_QueuedTrackComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_QueuedTrackComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _RouterLinkWithHref_2_3:import19.RouterLinkWithHref;
  _text_3:any;
  _text_4:any;
  _arr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_QueuedTrackComponent2,renderType_QueuedTrackComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'li',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n						',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'a',(null as any));
    this._RouterLinkWithHref_2_3 = new import19.RouterLinkWithHref(this.parent.parent.parentInjector.get(import20.Router),this.parent.parent.parentInjector.get(import21.ActivatedRoute),this.parent.parent.parentInjector.get(import22.LocationStrategy));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n					',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._arr_0 = import4.pureProxy3((p0:any,p1:any,p2:any):any[] => {
      return [
        p0,
        p1,
        p2
      ]
      ;
    });
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.RouterLinkWithHref) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._RouterLinkWithHref_2_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_1:any = this._arr_0('/artist',this.context.$implicit.MusicProvider.Identifier,this.context.$implicit.Link);
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._RouterLinkWithHref_2_3.routerLink = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_2_3.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = this._RouterLinkWithHref_2_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_2,'href',this.viewUtils.sanitizer.sanitize(import16.SecurityContext.URL,currVal_2));
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import4.interpolate(1,'',this.context.$implicit.Name,'');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_2_3.ngOnDestroy();
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_2_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_QueuedTrackComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_QueuedTrackComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_QueuedTrackComponent3 extends import1.AppView<any> {
  _el_0:any;
  _RouterLinkWithHref_0_3:import19.RouterLinkWithHref;
  _text_1:any;
  _arr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_QueuedTrackComponent3,renderType_QueuedTrackComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'a',(null as any));
    this._RouterLinkWithHref_0_3 = new import19.RouterLinkWithHref(this.parent.parentInjector.get(import20.Router),this.parent.parentInjector.get(import21.ActivatedRoute),this.parent.parentInjector.get(import22.LocationStrategy));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._arr_0 = import4.pureProxy3((p0:any,p1:any,p2:any):any[] => {
      return [
        p0,
        p1,
        p2
      ]
      ;
    });
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.RouterLinkWithHref) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._RouterLinkWithHref_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_1:any = this._arr_0('/album',((this.parent.context.queuedTrack == (null as any))? (null as any): ((this.parent.context.queuedTrack.Track == (null as any))? (null as any): this.parent.context.queuedTrack.Track.Album.MusicProvider.Identifier)),((this.parent.context.queuedTrack == (null as any))? (null as any): ((this.parent.context.queuedTrack.Track == (null as any))? (null as any): this.parent.context.queuedTrack.Track.Album.Link)));
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._RouterLinkWithHref_0_3.routerLink = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_0_3.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = this._RouterLinkWithHref_0_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_0,'href',this.viewUtils.sanitizer.sanitize(import16.SecurityContext.URL,currVal_2));
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import4.interpolate(1,'',((this.parent.context.queuedTrack == (null as any))? (null as any): ((this.parent.context.queuedTrack.Track == (null as any))? (null as any): ((this.parent.context.queuedTrack.Track.Album == (null as any))? (null as any): this.parent.context.queuedTrack.Track.Album.Name))),'');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_1,currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_0_3.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_0_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_QueuedTrackComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_QueuedTrackComponent3(viewUtils,parentInjector,declarationEl);
}
class _View_QueuedTrackComponent4 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _NgClass_0_4:import23.NgClass;
  _OpinionButtonsComponent_0_5:import24.OpinionButtonsComponent;
  /*private*/ _expr_2:any;
  _map_0:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_QueuedTrackComponent4,renderType_QueuedTrackComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'opinion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','col-xs-4 text-right');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import25.viewFactory_OpinionButtonsComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._NgClass_0_4 = new import23.NgClass(this.parent.parentInjector.get(import18.IterableDiffers),this.parent.parentInjector.get(import26.KeyValueDiffers),new import27.ElementRef(this._el_0),this.renderer);
    this._OpinionButtonsComponent_0_5 = new import24.OpinionButtonsComponent();
    this._appEl_0.initComponent(this._OpinionButtonsComponent_0_5,[],compView_0);
    compView_0.create(this._OpinionButtonsComponent_0_5,[],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'like',this.eventHandler(this._handle_like_0_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_0,'veto',this.eventHandler(this._handle_veto_0_1.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    this._map_0 = import4.pureProxy1((p0:any):{[key: string]:any} => {
      return {'has-votes': p0};
    });
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    const subscription_0:any = this._OpinionButtonsComponent_0_5.veto.subscribe(this.eventHandler(this._handle_veto_0_1.bind(this)));
    const subscription_1:any = this._OpinionButtonsComponent_0_5.like.subscribe(this.eventHandler(this._handle_like_0_0.bind(this)));
    this.init([].concat([this._el_0]),[this._el_0],[
      disposable_0,
      disposable_1
    ]
    ,[
      subscription_0,
      subscription_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import23.NgClass) && (0 === requestNodeIndex))) { return this._NgClass_0_4; }
    if (((token === import24.OpinionButtonsComponent) && (0 === requestNodeIndex))) { return this._OpinionButtonsComponent_0_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = 'col-xs-4 text-right';
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgClass_0_4.klass = currVal_2;
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._map_0(((this.parent.context.queuedTrack.LikeCount + this.parent.context.queuedTrack.VetoCount) > 0));
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgClass_0_4.ngClass = currVal_3;
      this._expr_3 = currVal_3;
    }
    if (!throwOnChange) { this._NgClass_0_4.ngDoCheck(); }
    const currVal_4:any = this.parent.context.queuedTrack;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._OpinionButtonsComponent_0_5.track = currVal_4;
      this._expr_4 = currVal_4;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._OpinionButtonsComponent_0_5.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_like_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.like()) !== false);
    return (true && pd_0);
  }
  private _handle_veto_0_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.veto()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_QueuedTrackComponent4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_QueuedTrackComponent4(viewUtils,parentInjector,declarationEl);
}
class _View_QueuedTrackComponent5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _QueueTrackButtonComponent_2_4:import28.QueueTrackButtonComponent;
  _text_3:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_QueuedTrackComponent5,renderType_QueuedTrackComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','col-xs-4 text-right');
    this._text_1 = this.renderer.createText(this._el_0,'\n				',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'queue-track-button',(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import29.viewFactory_QueueTrackButtonComponent0(this.viewUtils,this.injector(2),this._appEl_2);
    this._QueueTrackButtonComponent_2_4 = new import28.QueueTrackButtonComponent(this.parent.parentInjector.get(import8.QueueService));
    this._appEl_2.initComponent(this._QueueTrackButtonComponent_2_4,[],compView_2);
    compView_2.create(this._QueueTrackButtonComponent_2_4,[],(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n			',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import28.QueueTrackButtonComponent) && (2 === requestNodeIndex))) { return this._QueueTrackButtonComponent_2_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.parent.context.queuedTrack.Track;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._QueueTrackButtonComponent_2_4.track = currVal_0;
      this._expr_0 = currVal_0;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._QueueTrackButtonComponent_2_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_QueuedTrackComponent5(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_QueuedTrackComponent5(viewUtils,parentInjector,declarationEl);
}
class _View_QueuedTrackComponent6 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _pipe_async_0:import30.AsyncPipe;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_QueuedTrackComponent6,renderType_QueuedTrackComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._pipe_async_0 = new import30.AsyncPipe(this.parent.ref);
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    this.detectContentChildrenChanges(throwOnChange);
    valUnwrapper.reset();
    const currVal_0:any = import4.interpolate(1,'',valUnwrapper.unwrap(this._pipe_async_0.transform(this.parent.context.queuedTrack.fullName)),'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_0,currVal_0))) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._pipe_async_0.ngOnDestroy();
  }
}
function viewFactory_QueuedTrackComponent6(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_QueuedTrackComponent6(viewUtils,parentInjector,declarationEl);
}
class _View_QueuedTrackComponent7 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  /*private*/ _expr_0:any;
  _pipe_async_0:import30.AsyncPipe;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_QueuedTrackComponent7,renderType_QueuedTrackComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'a',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','user-link dark top');
    this.renderer.setElementAttribute(this._el_0,'target','_blank');
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'img',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._pipe_async_0 = new import30.AsyncPipe(this.parent.ref);
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this.parent.context.queuedTrack.url;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_0,'href',this.viewUtils.sanitizer.sanitize(import16.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    valUnwrapper.reset();
    const currVal_1:any = import4.interpolate(1,'',valUnwrapper.unwrap(this._pipe_async_0.transform(this.parent.context.queuedTrack.fullName)),'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_1,currVal_1))) {
      this.renderer.setText(this._text_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = ((this.parent.context.queuedTrack == (null as any))? (null as any): this.parent.context.queuedTrack.userPhotoUrl);
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_2,'src',this.viewUtils.sanitizer.sanitize(import16.SecurityContext.URL,currVal_2));
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._pipe_async_0.ngOnDestroy();
  }
}
function viewFactory_QueuedTrackComponent7(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_QueuedTrackComponent7(viewUtils,parentInjector,declarationEl);
}
class _View_QueuedTrackComponent8 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_QueuedTrackComponent8,renderType_QueuedTrackComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,' text: ',this.parent.context.queuedTrack.Reason,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_QueuedTrackComponent8(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_QueuedTrackComponent8(viewUtils,parentInjector,declarationEl);
}
class _View_QueuedTrackComponent9 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _pipe_date_0_0:any;
  _pipe_date_0_1:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_QueuedTrackComponent9,renderType_QueuedTrackComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._pipe_date_0_0 = import4.pureProxy2((<_View_QueuedTrackComponent0>this.parent)._pipe_date_0.transform.bind((<_View_QueuedTrackComponent0>this.parent)._pipe_date_0));
    this._pipe_date_0_1 = import4.pureProxy1((<_View_QueuedTrackComponent0>this.parent)._pipe_date_0.transform.bind((<_View_QueuedTrackComponent0>this.parent)._pipe_date_0));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    this.detectContentChildrenChanges(throwOnChange);
    valUnwrapper.reset();
    const currVal_0:any = import4.interpolate(2,', played at ',valUnwrapper.unwrap(import4.castByValue(this._pipe_date_0_0,(<_View_QueuedTrackComponent0>this.parent)._pipe_date_0.transform)(this.parent.context.queuedTrack.StartedPlayingDateTime,'HH:mm')),' on ',valUnwrapper.unwrap(import4.castByValue(this._pipe_date_0_1,(<_View_QueuedTrackComponent0>this.parent)._pipe_date_0.transform)(this.parent.context.queuedTrack.StartedPlayingDateTime)),'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_0,currVal_0))) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_QueuedTrackComponent9(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_QueuedTrackComponent9(viewUtils,parentInjector,declarationEl);
}
class _View_QueuedTrackComponent10 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import12.NgIf;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _anchor_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _TemplateRef_9_5:any;
  _NgIf_9_6:import12.NgIf;
  _text_10:any;
  _text_11:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_QueuedTrackComponent10,renderType_QueuedTrackComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n				',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','badge badge-like user-list-container');
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._appEl_4 = new import2.AppElement(4,2,this,this._anchor_4);
    this._TemplateRef_4_5 = new import14.TemplateRef_(this._appEl_4,viewFactory_QueuedTrackComponent11);
    this._NgIf_4_6 = new import12.NgIf(this._appEl_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText(this._el_2,'\n				',(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n				',(null as any));
    this._el_7 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','badge badge-veto user-list-container');
    this._text_8 = this.renderer.createText(this._el_7,'',(null as any));
    this._anchor_9 = this.renderer.createTemplateAnchor(this._el_7,(null as any));
    this._appEl_9 = new import2.AppElement(9,7,this,this._anchor_9);
    this._TemplateRef_9_5 = new import14.TemplateRef_(this._appEl_9,viewFactory_QueuedTrackComponent12);
    this._NgIf_9_6 = new import12.NgIf(this._appEl_9.vcRef,this._TemplateRef_9_5);
    this._text_10 = this.renderer.createText(this._el_7,'\n				',(null as any));
    this._text_11 = this.renderer.createText(this._el_0,'\n			',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._anchor_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._anchor_9,
      this._text_10,
      this._text_11
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import12.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6; }
    if (((token === import14.TemplateRef) && (9 === requestNodeIndex))) { return this._TemplateRef_9_5; }
    if (((token === import12.NgIf) && (9 === requestNodeIndex))) { return this._NgIf_9_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = ((this.parent.context.queuedTrack == (null as any))? (null as any): this.parent.context.queuedTrack.LikeCount);
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgIf_4_6.ngIf = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_3:any = ((this.parent.context.queuedTrack == (null as any))? (null as any): this.parent.context.queuedTrack.VetoCount);
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgIf_9_6.ngIf = currVal_3;
      this._expr_3 = currVal_3;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'\n					',this.parent.context.queuedTrack.LikeCount,'\n					');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_3,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_2:any = import4.interpolate(1,'\n					',this.parent.context.queuedTrack.VetoCount,'\n					');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_8,currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_QueuedTrackComponent10(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_QueuedTrackComponent10(viewUtils,parentInjector,declarationEl);
}
class _View_QueuedTrackComponent11 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _UserListComponent_0_4:import31.UserListComponent;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_QueuedTrackComponent11,renderType_QueuedTrackComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'user-list',(null as any));
    this.renderer.setElementAttribute(this._el_0,'position','top');
    this.renderer.setElementAttribute(this._el_0,'title','Likes');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import32.viewFactory_UserListComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._UserListComponent_0_4 = new import31.UserListComponent();
    this._appEl_0.initComponent(this._UserListComponent_0_4,[],compView_0);
    compView_0.create(this._UserListComponent_0_4,[],(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import31.UserListComponent) && (0 === requestNodeIndex))) { return this._UserListComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = ((this.parent.parent.context.queuedTrack == (null as any))? (null as any): this.parent.parent.context.queuedTrack.Likes);
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._UserListComponent_0_4.opinions = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = 'Likes';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._UserListComponent_0_4.title = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_QueuedTrackComponent11(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_QueuedTrackComponent11(viewUtils,parentInjector,declarationEl);
}
class _View_QueuedTrackComponent12 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _UserListComponent_0_4:import31.UserListComponent;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_QueuedTrackComponent12,renderType_QueuedTrackComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'user-list',(null as any));
    this.renderer.setElementAttribute(this._el_0,'position','top');
    this.renderer.setElementAttribute(this._el_0,'title','Vetoes');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import32.viewFactory_UserListComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._UserListComponent_0_4 = new import31.UserListComponent();
    this._appEl_0.initComponent(this._UserListComponent_0_4,[],compView_0);
    compView_0.create(this._UserListComponent_0_4,[],(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import31.UserListComponent) && (0 === requestNodeIndex))) { return this._UserListComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = ((this.parent.parent.context.queuedTrack == (null as any))? (null as any): this.parent.parent.context.queuedTrack.Vetoes);
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._UserListComponent_0_4.opinions = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = 'Vetoes';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._UserListComponent_0_4.title = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_QueuedTrackComponent12(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_QueuedTrackComponent12(viewUtils,parentInjector,declarationEl);
}